#!/usr/bin/env node
'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { hashObject, fail } = require('./lib/common');
const { assertConsumableGraph } = require('./lib/graph-normalization');
const { actionLabel, localizeIssue } = require('./lib/dashboard-localization');
const { buildFingerprint, compareFingerprint } = require('./lib/fingerprint');
const { actionKey } = require('./lib/graph-store');
const { assessAction } = require('./lib/safety');
const { resolveSyntheticAction } = require('./lib/synthetic-data');

function requestedScope(argv = process.argv.slice(2)) {
  const index = argv.findIndex(value => value === '--scope');
  if (index >= 0) return argv[index + 1] || null;
  const inline = argv.find(value => value.startsWith('--scope='));
  return inline ? inline.slice('--scope='.length) : null;
}

const scope = requestedScope();
const help = process.argv.includes('--help') || process.argv.includes('-h');
if (help || !scope) {
  console.log(JSON.stringify({
    schemaVersion: 1,
    ok: help,
    code: help ? null : 'SELF_TEST_SCOPE_REQUIRED',
    message: '请选择自测范围；日常 Restore 修改优先运行轻量专项，完成后再显式运行一次全量自测。',
    commands: {
      restore: 'node scripts/self-test.js --scope restore',
      protocol: 'node scripts/self-test.js --scope protocol',
      full: 'node scripts/self-test.js --scope full'
    }
  }, null, 2));
  process.exit(help ? 0 : 2);
}
if (scope === 'restore') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'restore-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'protocol') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'protocol-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope !== 'full') {
  console.error(JSON.stringify({ schemaVersion: 1, ok: false, error: { code: 'SELF_TEST_SCOPE_INVALID', message: `Unsupported self-test scope: ${scope}` } }));
  process.exit(2);
}
const suiteStartedMs = Date.now();
process.stderr.write('[SMAP] 正在运行全量自测；开发迭代请优先使用 --scope restore。\n');

const scripts = __dirname; const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'smap-self-test-')); const bin = path.join(temp, 'bin'); fs.mkdirSync(bin); const stateFile = path.join(temp, 'state'); const restartModeFile = path.join(temp, 'restart-mode'); const restartCountFile = path.join(temp, 'restart-count'); fs.writeFileSync(stateFile, 'home'); fs.writeFileSync(restartModeFile, ''); fs.writeFileSync(restartCountFile, '0');
const fakeHdc = `#!/usr/bin/env node
const fs=require('fs'); const a=process.argv.slice(2); const stateFile=process.env.SMAP_FAKE_STATE; const i=a[0]==='-t'?2:0; const c=a.slice(i);
if(c[0]==='shell'&&c[1]==='uitest'&&c[2]==='--version'){console.log('uitest 1.0');process.exit(0)}
if(c[0]==='shell'&&c[1]==='aa'&&c[2]==='dump'){console.log('AbilityRecord ID #1\\n state #FOREGROUND\\n ability type [PAGE]\\n bundle name [com.example.demo]\\n main name [EntryAbility]');process.exit(0)}
if(c[0]==='shell'&&c[1]==='uitest'&&c[2]==='uiInput'){if(c[3]==='click'){const x=Number(c[4]);const s=fs.readFileSync(stateFile,'utf8').trim();if(s==='action-error')process.exit(2);if((s==='businessmodal'||s==='nuisance'||s==='startup-popup')&&x>=300)fs.writeFileSync(stateFile,s==='startup-popup'?'home':'profile');else if(x<100)fs.writeFileSync(stateFile,'profile-render-1');else if(x<200)fs.writeFileSync(stateFile,'businessmodal');else if(x<300)fs.writeFileSync(stateFile,'nuisance')}else if(c[3]==='keyEvent'&&String(c[4]).toUpperCase()==='BACK'){const s=fs.readFileSync(stateFile,'utf8').trim();if(s==='profile')fs.writeFileSync(stateFile,'home');else if(['businessmodal','nuisance'].includes(s))fs.writeFileSync(stateFile,'profile')}process.exit(0)}
if(c[0]==='shell'&&c[1]==='aa'){if(c[2]==='start'){const countFile=process.env.SMAP_FAKE_RESTART_COUNT;fs.writeFileSync(countFile,String(Number(fs.readFileSync(countFile,'utf8'))+1));const s=fs.readFileSync(stateFile,'utf8').trim();const mode=fs.readFileSync(process.env.SMAP_FAKE_RESTART_MODE,'utf8').trim();if(mode==='startup-popup')fs.writeFileSync(stateFile,'startup-popup');else if(mode!=='preserve'&&!['goal','startup-popup'].includes(s))fs.writeFileSync(stateFile,'home')}process.exit(0)}
if(c[0]==='shell'&&c[1]==='uitest'&&['screenCap','dumpLayout'].includes(c[2]))process.exit(0);
if(c[0]==='file'&&c[1]==='recv'){const out=c[3];fs.mkdirSync(require('path').dirname(out),{recursive:true});const s=fs.readFileSync(stateFile,'utf8').trim();if(c[2].endsWith('.png')){fs.writeFileSync(out,Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.from(s)]));if(s==='profile-render-1')fs.writeFileSync(stateFile,'profile-render-2');else if(s==='profile-render-2')fs.writeFileSync(stateFile,'profile');else if(s.startsWith('animated-'))fs.writeFileSync(stateFile,'animated-'+(Number(s.split('-')[1])+1))}else{const texts=s==='profile'?['我的','设置']:s==='goal'?['账号与安全','修改密码']:s==='businessmodal'?['筛选条件','关闭']:s==='nuisance'?['活动提示','稍后']:s==='startup-popup'?['启动公告','关闭']:s==='loading'||s.startsWith('profile-render-')?['加载中']:['首页','我的'];fs.writeFileSync(out,JSON.stringify({type:s.includes('popup')||s.includes('modal')||s==='nuisance'?'Dialog':'Page',children:texts.map((text,n)=>({type:'Text',resourceId:'id'+n,text,bounds:[0,n*100,100,n*100+50]}))}))}process.exit(0)}
process.exit(0);`;
fs.writeFileSync(path.join(bin, 'hdc'), fakeHdc, { mode: 0o755 }); fs.writeFileSync(path.join(bin, 'devecocli'), '#!/usr/bin/env node\nconsole.log("fake-device connected")\n', { mode: 0o755 });
const env = { ...process.env, PATH: `${bin}:${process.env.PATH}`, SMAP_HDC: path.join(bin, 'hdc'), SMAP_DEVECOCLI: path.join(bin, 'devecocli'), SMAP_FAKE_STATE: stateFile, SMAP_FAKE_RESTART_MODE: restartModeFile, SMAP_FAKE_RESTART_COUNT: restartCountFile, SMAP_RESTART_SETTLE_MS: '1', SMAP_OBSERVATION_INITIAL_DELAY_MS: '0', SMAP_OBSERVATION_SAMPLE_INTERVAL_MS: '0', SMAP_OBSERVATION_TIMEOUT_MS: '1000', SMAP_OBSERVATION_VISUAL_FALLBACK_MS: '0' };
function run(file, args = [], allowFailure = false) { const result = spawnSync(path.join(scripts, file), args, { encoding: 'utf8', env, timeout: 60000 }); if (!allowFailure && result.status !== 0) throw new Error(`${file} failed (${result.status}, signal=${result.signal}, error=${result.error?.code || 'none'}): ${result.stderr}\n${result.stdout}`); let json = null; try { json = JSON.parse(result.stdout); } catch {} return { ...result, json }; }
function sha(file) { return `sha256:${crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}`; }
function prepareContext(scanDir, contextId) { const shown = run('show-plan.js', ['--scan-dir', scanDir]).json; run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', shown.planHash]); const prepared = run('prepare-context.js', ['--scan-dir', scanDir, '--context', contextId]).json; const obs = prepared.observation.observationId; run('context.js', ['verify', '--scan-dir', scanDir, '--context', contextId, '--observation-id', obs]); run('context.js', ['start', '--scan-dir', scanDir, '--context', contextId]); return obs; }

let tests = 0; function check(value, expected) { assert.deepEqual(value, expected); tests += 1; }
try {
  check(actionLabel({ type: 'tap', target: '我的' }), '点击 · 我的'); check(actionLabel({ type: 'keyEvent', key: 'BACK' }), '按键 · 返回键'); check(localizeIssue({ type: 'EDGE_ENDPOINT_UNRESOLVED', contextId: 'guest', runId: 'run-1', sourceEdgeId: 'edge-1' }).typeLabel, '跳转端点无法解析');
  const fingerprintLayout = { type: 'Page', children: [{ type: 'Text', text: '相同布局' }] }; check(compareFingerprint(buildFingerprint(fingerprintLayout, { bundleName: 'demo', ability: 'Entry' }, { screenshotSha256: 'sha256:a' }), buildFingerprint(fingerprintLayout, { bundleName: 'demo', ability: 'Entry' }, { screenshotSha256: 'sha256:b' })), 'PROBABLE');
  check(actionKey({ type: 'tap', x: 10, y: 10 }) === actionKey({ type: 'tap', x: 900, y: 900 }), false);
  check(assessAction({ type: 'inputText', value: 'fixed' }, { environment: 'test' }).replayPolicy, 'NONREPEATABLE'); const syntheticAction = { type: 'inputText', value: '', syntheticSpec: { type: 'email', prefix: 'smap' } }; check(assessAction(syntheticAction, { environment: 'test' }).replayPolicy, 'REGENERATE_SYNTHETIC'); check(resolveSyntheticAction(syntheticAction, 'one').value === resolveSyntheticAction(syntheticAction, 'two').value, false);
  check(run('probe-env.sh', ['--device', 'fake-device']).json.ok, true);
  const root = path.join(temp, 'app-map'); run('init-app-root.js', ['--app-map-root', root, '--bundle-name', 'com.example.demo', '--entry-ability', 'EntryAbility', '--environment', 'test']);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', '../escape', '--device', 'fake-device'], true).status !== 0, true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-module', '--device', 'fake-device', '--scan-scope', 'module'], true).status !== 0, true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-wrong-profile', '--device', 'fake-device', '--profile', 'goal'], true).stderr.includes('PROFILE_MODE_MISMATCH'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-multi-context', '--device', 'fake-device', '--contexts', 'guest,authenticated'], true).stderr.includes('CONTEXT_INVALID'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-bad-navigation', '--device', 'fake-device', '--navigation-policy', 'unknown'], true).stderr.includes('NAVIGATION_POLICY_INVALID'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-internal-budget', '--device', 'fake-device', '--budget', JSON.stringify({ maxDeviceActions: 1 })], true).stderr.includes('BUDGET_FIELD_INTERNAL'), true);
  const scanDir = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-exploration', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const displayedPlan = run('show-plan.js', ['--scan-dir', scanDir]).json; check(displayedPlan.plan.schemaVersion, 3); check(displayedPlan.plan.profileSelection.availableProfiles.length, 4); check(displayedPlan.plan.profileSelection.selectedProfile, 'standard'); check(displayedPlan.plan.profileSelection.availableProfiles.find(item => item.id === 'quick').budget.maxActiveMinutes, 10); check(displayedPlan.plan.profileSelection.availableProfiles.find(item => item.id === 'goal').applicable, false); check(displayedPlan.plan.context.id, 'guest'); check(displayedPlan.plan.userConfiguration.maxActiveMinutes, 20); check(displayedPlan.plan.execution.verificationRule, 'CANONICAL_SCREEN_PATH'); check(displayedPlan.plan.timeExpectation.wallClockGuarantee, false); check(run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', 'sha256:stale'], true).status !== 0, true);
  const configuredPlan = run('context.js', ['configure-plan', '--scan-dir', scanDir, '--profile', 'deep', '--budget', JSON.stringify({ maxActiveMinutes: 30 })]).json; check(configuredPlan.plan.profileSelection.selectedProfile, 'deep'); check(configuredPlan.plan.profileSelection.hasBudgetOverrides, true); check(configuredPlan.plan.derivedExecutionLimits.maxActiveMinutes, 30); check(configuredPlan.plan.profileSelection.budgetOverrides[0].actualValue, 30); check(run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', displayedPlan.planHash], true).stderr.includes('PLAN_HASH_MISMATCH'), true); const refreshedPlan = run('show-plan.js', ['--scan-dir', scanDir]).json; check(refreshedPlan.planHash, configuredPlan.planHash);
  run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', configuredPlan.planHash]); check(run('context.js', ['configure-plan', '--scan-dir', scanDir, '--profile', 'quick'], true).stderr.includes('RUN_STATE_INVALID'), true); fs.writeFileSync(stateFile, 'startup-popup');
  const prepared = run('prepare-context.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest']).json; check(fs.readFileSync(stateFile, 'utf8'), 'startup-popup'); check(prepared.requiresIdentityConfirmation, undefined);
  const stableCheck = run('prepare-context.js', ['observe-again', '--scan-dir', scanDir, '--context', 'guest', '--preparation-id', prepared.preparation.preparationId, '--observation-id', prepared.observation.observationId]).json; check(stableCheck.preparation.stabilityChecks.length, 1);
  const cleaned = run('prepare-context.js', ['dismiss-popup', '--scan-dir', scanDir, '--context', 'guest', '--preparation-id', stableCheck.preparation.preparationId, '--observation-id', stableCheck.observation.observationId, '--dismiss-action', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json; check(fs.readFileSync(stateFile, 'utf8'), 'home'); check(cleaned.preparation.interruptions.length, 1);
  const preflight = cleaned.observation.observationId; run('context.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--observation-id', preflight]); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']); run('context.js', ['pause', '--scan-dir', scanDir, '--reason-code', 'TEST_HUMAN_WAIT']); const pausedDuration = JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')).activeDurationMs; Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 20); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')).activeDurationMs, pausedDuration); check(run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'context-verification'], true).status !== 0, true); fs.writeFileSync(stateFile, 'loading'); check(run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'scan'], true).status !== 0, true); check(fs.readdirSync(path.join(scanDir, 'evidence', 'logs')).some(name => name.endsWith('-stability-timeout.json')), true); fs.writeFileSync(stateFile, 'animated-1'); const dynamicObservation = run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'scan']).json.observation; check(dynamicObservation.stability.status, 'LAYOUT_STABLE_VISUAL_DYNAMIC'); check(dynamicObservation.stability.sampleCount, 3); fs.writeFileSync(stateFile, 'home'); const visual1 = run('graph.js', ['upsert-visual', '--scan-dir', scanDir, '--context', 'guest', '--root', 'true', '--observation-id', preflight, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id;
  const rootState = run('graph.js', ['upsert-reachable', '--scan-dir', scanDir, '--context', 'guest', '--root', 'true', '--visual-state-id', visual1, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  fs.writeFileSync(restartModeFile, 'startup-popup'); const recurringFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'home/recurring-startup-popup', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item; const recurringClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; const restartsBeforeRecurringRestore = Number(fs.readFileSync(restartCountFile, 'utf8')); let recurringAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', recurringFrontier.id, '--claim-token', recurringClaim.claimToken]).json.attempt; check(recurringAttempt.status, 'AWAITING_RESTORE_REVIEW'); const restartsAfterRecurringRestore = Number(fs.readFileSync(restartCountFile, 'utf8')); check(restartsAfterRecurringRestore, restartsBeforeRecurringRestore + 1); const legacyRestoreFile = path.join(scanDir, 'evidence', 'restores', `${recurringAttempt.activeRestoreId}.json`); const legacyRestore = JSON.parse(fs.readFileSync(legacyRestoreFile, 'utf8')); legacyRestore.schemaVersion = 1; delete legacyRestore.checkpoint; fs.writeFileSync(legacyRestoreFile, `${JSON.stringify(legacyRestore, null, 2)}\n`); const recurringReview = run('execute-frontier.js', ['review-restore', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId, '--observation-id', recurringAttempt.reviewObservationId, '--disposition', 'DISMISSIBLE_POPUP', '--dismiss-action', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json; recurringAttempt = recurringReview.attempt; check(recurringAttempt.status, 'READY_FOR_ACTION'); check(Number(fs.readFileSync(restartCountFile, 'utf8')), restartsAfterRecurringRestore); check(recurringAttempt.interruptions[0].afterObservationId != null, true); check(recurringAttempt.restoreResults.length, 1); check(recurringAttempt.restoreResults[0].status, 'SUCCEEDED'); recurringAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId]).json.attempt; const recurringResolved = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId, '--observation-id', recurringAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json; check(recurringResolved.attempt.status, 'NO_STATE_CHANGE'); fs.writeFileSync(restartModeFile, '');
  check(run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'internal/wait', '--candidate', JSON.stringify({ type: 'wait', durationMs: 500 })], true).status !== 0, true);
  const noChangeFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'home/no-op', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item; const noChangeClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(noChangeClaim.id, noChangeFrontier.id);
  let noChangeAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', noChangeFrontier.id, '--claim-token', noChangeClaim.claimToken]).json.attempt; noChangeAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId]).json.attempt; check(noChangeAttempt.sourceComparison, 'EXACT'); check(run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId, '--observation-id', noChangeAttempt.reviewObservationId, '--disposition', 'PAGE'], true).status !== 0, true); const noChangeReview = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId, '--observation-id', noChangeAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json; check(noChangeReview.edgeCreated, false); check(noChangeReview.attempt.status, 'NO_STATE_CHANGE'); check(noChangeReview.frontier.reasonCode, 'NO_STATE_CHANGE'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'graph.json'), 'utf8')).edges.length, 0);
  const frontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'bottom/profile', '--candidate', JSON.stringify({ type: 'tap', target: '我的', fallbackBounds: [0, 0, 100, 100], routeTransition: true })]).json.item;
  const profileClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(profileClaim.id, frontier.id);
  let attempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', frontier.id, '--claim-token', profileClaim.claimToken]).json.attempt; check(attempt.status, 'READY_FOR_ACTION'); const duplicatePrepare = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', frontier.id, '--claim-token', profileClaim.claimToken]).json; check(duplicatePrepare.reused, true); check(duplicatePrepare.attempt.attemptId, attempt.attemptId);
  attempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId]).json.attempt; check(attempt.status, 'AWAITING_OUTCOME_REVIEW'); const stabilizedActionObservation = JSON.parse(fs.readFileSync(path.join(scanDir, 'evidence', 'observations', attempt.reviewObservationId, 'observation.json'), 'utf8')); check(stabilizedActionObservation.stability.status, 'STABLE'); check(stabilizedActionObservation.stability.sampleCount >= 4, true); check(stabilizedActionObservation.trigger, 'ACTION');
  attempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId, '--observation-id', attempt.reviewObservationId, '--disposition', 'TRANSIENT']).json.attempt; check(attempt.stabilityChecks.length, 1);
  attempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId, '--observation-id', attempt.reviewObservationId, '--disposition', 'PAGE']).json.attempt; check(attempt.status, 'READY_TO_COMMIT');
  const committed = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', attempt.attemptId, '--logical-screen-key', 'profile', '--name', '我的']).json; check(committed.attempt.status, 'COMMITTED'); check(committed.edge.attemptId, attempt.attemptId); check(committed.edge.replayability, 'UNSTABLE'); check(run('next-work.js', ['--scan-dir', scanDir, '--context', 'guest']).json.decision, 'VERIFY');
  const backVerified = run('back-capability.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--to-reachable-state-id', rootState]).json; check(backVerified.backCapability.verificationStatus, 'EXACT'); check(fs.readFileSync(stateFile, 'utf8'), 'home'); check(run('back-capability.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.length, 1);
  const committedGraphFile = path.join(scanDir, 'contexts', 'guest', 'graph.json'); const damagedGraph = JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')); damagedGraph.edges = []; damagedGraph.reachableStates = damagedGraph.reachableStates.filter(x => x.id !== committed.reachableState.id); damagedGraph.visualStates = damagedGraph.visualStates.filter(x => x.id !== committed.visualState.id); damagedGraph.logicalScreens = damagedGraph.logicalScreens.filter(x => x.id !== 'profile'); fs.writeFileSync(committedGraphFile, `${JSON.stringify(damagedGraph, null, 2)}\n`); run('context.js', ['pause', '--scan-dir', scanDir, '--reason-code', 'TEST_RECOVERY']); const recoveredGraph = JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')); check(recoveredGraph.edges.some(x => x.id === committed.edge.id), true); check(recoveredGraph.reachableStates.some(x => x.id === committed.reachableState.id), true); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']);
  const modalFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/filter', '--candidate', JSON.stringify({ type: 'tap', target: '筛选', fallbackBounds: [100, 0, 200, 100] })]).json.item; const modalClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(modalClaim.id, modalFrontier.id);
  let modalAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', modalFrontier.id, '--claim-token', modalClaim.claimToken]).json.attempt; modalAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', modalAttempt.attemptId]).json.attempt; modalAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', modalAttempt.attemptId, '--observation-id', modalAttempt.reviewObservationId, '--disposition', 'BUSINESS_MODAL']).json.attempt;
  const modalCommitted = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', modalAttempt.attemptId, '--logical-screen-key', 'profile-filter', '--name', '筛选条件']).json; check(modalCommitted.visualState.kind, 'modal'); check(modalCommitted.reachableState.depth.modalDepth, 1);
  const closeFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', modalCommitted.reachableState.id, '--candidate-group-key', 'filter/close', '--candidate', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json.item; const closeClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(closeClaim.id, closeFrontier.id);
  let closeAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', closeFrontier.id, '--claim-token', closeClaim.claimToken]).json.attempt; closeAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', closeAttempt.attemptId]).json.attempt; closeAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', closeAttempt.attemptId, '--observation-id', closeAttempt.reviewObservationId, '--disposition', 'PAGE']).json.attempt;
  const logicalConflict = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', closeAttempt.attemptId, '--logical-screen-key', 'profile-alias', '--name', '我的别名'], true); check(logicalConflict.status !== 0 && logicalConflict.stderr.includes('LOGICAL_SCREEN_CONFLICT'), true); check(JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')).logicalScreens.some(x => x.id === 'profile-alias'), false); const closeCommitted = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', closeAttempt.attemptId, '--logical-screen-key', 'profile', '--name', '我的']).json; check(closeCommitted.reachableState.depth.modalDepth, 0);
  const nuisanceFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/activity-tip', '--candidate', JSON.stringify({ type: 'tap', target: '活动入口', fallbackBounds: [200, 0, 300, 100] })]).json.item; const nuisanceClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(nuisanceClaim.id, nuisanceFrontier.id);
  let nuisanceAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', nuisanceFrontier.id, '--claim-token', nuisanceClaim.claimToken]).json.attempt; nuisanceAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', nuisanceAttempt.attemptId]).json.attempt;
  const nuisanceReviewed = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', nuisanceAttempt.attemptId, '--observation-id', nuisanceAttempt.reviewObservationId, '--disposition', 'DISMISSIBLE_POPUP', '--dismiss-action', JSON.stringify({ type: 'tap', target: '稍后', fallbackBounds: [300, 0, 400, 100] })]).json; check(nuisanceReviewed.edgeCreated, false); check(nuisanceReviewed.attempt.status, 'DISMISSED_NO_EDGE'); check(fs.readFileSync(stateFile, 'utf8'), 'profile');
  const failureFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/failure-recovery', '--candidate', JSON.stringify({ type: 'tap', target: '故障恢复测试', fallbackBounds: [400, 0, 500, 100] })]).json.item; const failureClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; const failureAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', failureFrontier.id, '--claim-token', failureClaim.claimToken]).json.attempt;
  fs.writeFileSync(stateFile, 'action-error'); check(run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', failureAttempt.attemptId], true).status !== 0, true); fs.writeFileSync(stateFile, 'profile'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'scan.json'), 'utf8')).status, 'PAUSED'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'attempts', `${failureAttempt.attemptId}.json`), 'utf8')).status, 'UNKNOWN_EFFECT');
  const unknownOperation = run('operation.js', ['list', '--scan-dir', scanDir]).json.items.find(item => item.owner?.type === 'ATTEMPT' && item.owner.id === failureAttempt.attemptId && item.status === 'UNKNOWN_OUTCOME'); check(Boolean(unknownOperation), true);
  const recoveryPreparation = run('prepare-context.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest']).json; const recoveryObservationId = recoveryPreparation.observation.observationId; run('operation.js', ['reconcile', '--scan-dir', scanDir, '--operation-id', unknownOperation.operationId, '--resolution', 'NO_EFFECT', '--observation-id', recoveryObservationId]);
  const retryableFailure = run('frontier.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.find(x => x.id === failureFrontier.id); check(retryableFailure.status, 'RETRYABLE'); check(retryableFailure.claimedAttemptId, null); run('context.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--observation-id', recoveryObservationId]); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']);
  let retryClaimResult = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json; while (retryClaimResult.decision === 'VERIFY') { run('verify-path.js', ['run', '--scan-dir', scanDir, '--context', 'guest', '--verification-id', retryClaimResult.verification.verificationId]); retryClaimResult = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json; } const retryClaim = retryClaimResult.item; run('frontier.js', ['resolve', '--scan-dir', scanDir, '--context', 'guest', '--id', retryClaim.id, '--status', 'FAILED', '--reason-code', 'TEST_FAILURE_RESOLVED']);
  fs.writeFileSync(restartModeFile, ''); for (const verification of run('verify-path.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.filter(item => item.status === 'PENDING')) run('verify-path.js', ['run', '--scan-dir', scanDir, '--context', 'guest', '--verification-id', verification.verificationId]);
  run('finalize-scan.js', ['--scan-dir', scanDir, '--status', 'COMPLETED']); const finalizedMetrics = JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')); check(finalizedMetrics.observationSamples > finalizedMetrics.observations, true); check(finalizedMetrics.observationStabilityWaitMs >= 0, true); check(finalizedMetrics.noStateChangeActions, 2); check(finalizedMetrics.verificationActions > 0, true); check(fs.readFileSync(path.join(scanDir, 'report.md'), 'utf8').includes('观测稳定性'), true); run('register-run.js', ['--scan-dir', scanDir]);
  fs.writeFileSync(stateFile, 'animated-1'); fs.writeFileSync(restartModeFile, 'preserve');
  const dynamicRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-dynamic-restore', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const dynamicRootObservationId = prepareContext(dynamicRun, 'guest'); const dynamicRootObservation = JSON.parse(fs.readFileSync(path.join(dynamicRun, 'evidence', 'observations', dynamicRootObservationId, 'observation.json'), 'utf8')); check(dynamicRootObservation.stability.status, 'LAYOUT_STABLE_VISUAL_DYNAMIC');
  const dynamicRootVisual = run('graph.js', ['upsert-visual', '--scan-dir', dynamicRun, '--context', 'guest', '--root', 'true', '--observation-id', dynamicRootObservationId, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id;
  const dynamicRootState = run('graph.js', ['upsert-reachable', '--scan-dir', dynamicRun, '--context', 'guest', '--root', 'true', '--visual-state-id', dynamicRootVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  fs.writeFileSync(restartModeFile, ''); fs.writeFileSync(stateFile, 'home');
  const dynamicFrontier = run('frontier.js', ['add', '--scan-dir', dynamicRun, '--context', 'guest', '--from-reachable-state-id', dynamicRootState, '--candidate-group-key', 'home/dynamic-restore', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item;
  const dynamicClaim = run('frontier.js', ['claim', '--scan-dir', dynamicRun, '--context', 'guest']).json.item;
  const dynamicPrepared = run('execute-frontier.js', ['prepare', '--scan-dir', dynamicRun, '--context', 'guest', '--frontier-id', dynamicFrontier.id, '--claim-token', dynamicClaim.claimToken]).json; let dynamicAttempt = dynamicPrepared.attempt; check(dynamicAttempt.status, 'AWAITING_RESTORE_REVIEW'); check(dynamicAttempt.restoreMismatch.comparison, 'PROBABLE'); check(dynamicPrepared.reviewRequest.dispositions.includes('EXPECTED_STATE_EQUIVALENT'), true);
  const dynamicReviewObservation = JSON.parse(fs.readFileSync(path.join(dynamicRun, 'evidence', 'observations', dynamicAttempt.reviewObservationId, 'observation.json'), 'utf8'));
  const equivalenceAssessment = { status: 'EXPECTED_STATE_EQUIVALENT', expectedReachableStateId: dynamicRootState, observedSha256: dynamicReviewObservation.stability.finalScreenshotSha256, rationale: '页面布局与语义一致，仅动态视觉内容变化' };
  dynamicAttempt = run('execute-frontier.js', ['review-restore', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId, '--observation-id', dynamicAttempt.reviewObservationId, '--disposition', 'EXPECTED_STATE_EQUIVALENT', '--visual-assessment', JSON.stringify(equivalenceAssessment)]).json.attempt;
  check(dynamicAttempt.status, 'READY_FOR_ACTION'); check(dynamicAttempt.restoreResults[0].equivalenceReviews.length, 1); check(dynamicAttempt.restoreResults[0].equivalenceReviews[0].observedSha256, equivalenceAssessment.observedSha256);
  dynamicAttempt = run('execute-frontier.js', ['act', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId]).json.attempt;
  const dynamicResolved = run('execute-frontier.js', ['review-outcome', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId, '--observation-id', dynamicAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json;
  check(dynamicResolved.attempt.status, 'NO_STATE_CHANGE'); check(run('finalize-scan.js', ['--scan-dir', dynamicRun, '--status', 'COMPLETED']).json.scan.status, 'COMPLETED'); fs.rmSync(dynamicRun, { recursive: true, force: true });
  fs.writeFileSync(stateFile, 'home'); fs.writeFileSync(restartModeFile, ''); const adaptiveRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-adaptive-cursor', '--device', 'fake-device', '--context', 'guest']).json.scanDir; const adaptiveObs = prepareContext(adaptiveRun, 'guest'); const adaptiveVisual = run('graph.js', ['upsert-visual', '--scan-dir', adaptiveRun, '--context', 'guest', '--root', 'true', '--observation-id', adaptiveObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; const adaptiveRoot = run('graph.js', ['upsert-reachable', '--scan-dir', adaptiveRun, '--context', 'guest', '--root', 'true', '--visual-state-id', adaptiveVisual, '--arrival-signature', '{}', '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  for (const group of ['noop-a', 'noop-b']) run('frontier.js', ['add', '--scan-dir', adaptiveRun, '--context', 'guest', '--from-reachable-state-id', adaptiveRoot, '--candidate-group-key', group, '--candidate', JSON.stringify({ type: 'tap', target: group, fallbackBounds: [400, 0, 500, 100] })]); const adaptiveRestarts = Number(fs.readFileSync(restartCountFile, 'utf8'));
  for (let index = 0; index < 2; index += 1) { const claim = run('frontier.js', ['claim', '--scan-dir', adaptiveRun, '--context', 'guest']).json.item; let current = run('execute-frontier.js', ['prepare', '--scan-dir', adaptiveRun, '--context', 'guest', '--frontier-id', claim.id, '--claim-token', claim.claimToken]).json.attempt; check(current.sourceAcquisitionMode, 'LIVE_CURSOR'); current = run('execute-frontier.js', ['act', '--scan-dir', adaptiveRun, '--context', 'guest', '--attempt-id', current.attemptId]).json.attempt; run('execute-frontier.js', ['review-outcome', '--scan-dir', adaptiveRun, '--context', 'guest', '--attempt-id', current.attemptId, '--observation-id', current.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']); }
  check(Number(fs.readFileSync(restartCountFile, 'utf8')), adaptiveRestarts); const adaptiveMetrics = JSON.parse(fs.readFileSync(path.join(adaptiveRun, 'contexts', 'guest', 'metrics.json'), 'utf8')); check(adaptiveMetrics.cursorReuseHits, 2); check(adaptiveMetrics.coldStarts, 1); check(run('finalize-scan.js', ['--scan-dir', adaptiveRun, '--status', 'COMPLETED']).json.scan.status, 'COMPLETED'); fs.rmSync(adaptiveRun, { recursive: true, force: true });
  fs.writeFileSync(stateFile, 'home'); const latestRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-latest-path', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir; const latestRootObs = prepareContext(latestRun, 'guest'); const latestRootVisual = run('graph.js', ['upsert-visual', '--scan-dir', latestRun, '--context', 'guest', '--root', 'true', '--observation-id', latestRootObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; const latestRootState = run('graph.js', ['upsert-reachable', '--scan-dir', latestRun, '--context', 'guest', '--root', 'true', '--visual-state-id', latestRootVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  const latestFrontier = run('frontier.js', ['add', '--scan-dir', latestRun, '--context', 'guest', '--from-reachable-state-id', latestRootState, '--candidate-group-key', 'bottom/profile', '--candidate', JSON.stringify({ type: 'tap', target: '我的', fallbackBounds: [0, 0, 100, 100], routeTransition: true })]).json.item; const latestClaim = run('frontier.js', ['claim', '--scan-dir', latestRun, '--context', 'guest']).json.item; let latestAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', latestRun, '--context', 'guest', '--frontier-id', latestFrontier.id, '--claim-token', latestClaim.claimToken]).json.attempt; latestAttempt = run('execute-frontier.js', ['act', '--scan-dir', latestRun, '--context', 'guest', '--attempt-id', latestAttempt.attemptId]).json.attempt; latestAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', latestRun, '--context', 'guest', '--attempt-id', latestAttempt.attemptId, '--observation-id', latestAttempt.reviewObservationId, '--disposition', 'PAGE']).json.attempt; run('commit-attempt.js', ['--scan-dir', latestRun, '--attempt-id', latestAttempt.attemptId, '--logical-screen-key', 'profile', '--name', '个人中心']); for (const verification of run('verify-path.js', ['list', '--scan-dir', latestRun, '--context', 'guest']).json.items.filter(item => item.status === 'PENDING')) run('verify-path.js', ['run', '--scan-dir', latestRun, '--context', 'guest', '--verification-id', verification.verificationId]); run('finalize-scan.js', ['--scan-dir', latestRun, '--status', 'COMPLETED']); run('register-run.js', ['--scan-dir', latestRun]);
  const unrelatedRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-unrelated-partial', '--device', 'fake-device', '--contexts', 'guest', '--app-version', '1.0', '--build-version', '10']).json.scanDir; prepareContext(unrelatedRun, 'guest'); run('finalize-scan.js', ['--scan-dir', unrelatedRun, '--status', 'PARTIAL']); run('register-run.js', ['--scan-dir', unrelatedRun]);
  check(run('context.js', ['manual-transition', '--scan-dir', scanDir, '--context', 'guest'], true).status !== 0, true);
  const timeline = fs.readFileSync(path.join(scanDir, 'timeline.jsonl'), 'utf8').trim().split('\n').map(JSON.parse); check(new Set(timeline.map(x => x.eventId)).size, timeline.length);
  const rebuilt = run('rebuild-run.js', ['--scan-dir', scanDir, '--output-dir', path.join(temp, 'rebuilt')]).json; check(rebuilt.ok, true);
  check(run('rebuild-run-index.js', ['--app-map-root', root]).json.indexed, 3);
  const rebuiltIndex = JSON.parse(fs.readFileSync(path.join(root, 'run-index.json'), 'utf8')); check(rebuiltIndex.appKey, 'com-example-demo-test'); const snapshot = run('build-snapshot.js', ['--app-map-root', root]).json; check(snapshot.manifest.status, 'PARTIAL'); check(snapshot.manifest.mapRevisionId, null); check(snapshot.manifest.aggregationPolicy, 'LATEST_OBSERVATION_WINS'); check(snapshot.manifest.mapRevisionIds.length, 3); check(snapshot.manifest.sourcePlans.guest.includes('scan-unrelated-partial'), true); check(fs.existsSync(path.join(root, 'snapshots', 'current.json')), true); check(fs.existsSync(path.join(snapshot.snapshotDir, 'manifest.json')), true);
  const snapshotMap = JSON.parse(fs.readFileSync(path.join(snapshot.snapshotDir, 'map.json'), 'utf8')); const snapshotGraph = snapshotMap.contexts.guest; check(snapshotGraph.logicalScreens.every(x => x.id.startsWith('ls-')), true); check(snapshotGraph.logicalScreens.find(x => x.semanticKey === 'profile').name, '个人中心'); check(snapshotGraph.reachableStates.every(x => x.id.startsWith('rs-')), true); check(snapshotGraph.reachableStates.filter(x => x.arrivalSignature.expectedBackReachableStateId).every(x => x.arrivalSignature.expectedBackReachableStateId.startsWith('rs-')), true); const latestPathEdge = snapshotGraph.edges.find(edge => edge.action?.target === '我的'); check(latestPathEdge.evidence.sourceRunId, 'scan-latest-path'); check(latestPathEdge.provenance.some(item => item.runId === 'scan-exploration'), true); check(latestPathEdge.provenance.some(item => item.runId === 'scan-latest-path'), true); check(snapshotGraph.edges.some(edge => edge.action?.target === '筛选'), true);
  const dashboard = run('build-dashboard.js', ['--app-map-root', root]).json; check(fs.existsSync(dashboard.dashboardPath), true); const dashboardHtml = fs.readFileSync(dashboard.dashboardPath, 'utf8'); check(dashboardHtml.includes('__SMAP_DASHBOARD_DATA__'), false); check(dashboardHtml.includes(snapshot.manifest.generationId), true);
  const embedded = dashboardHtml.match(/<script id="dashboard-data" type="application\/json">([\s\S]*?)<\/script>/); check(Boolean(embedded), true); const dashboardData = JSON.parse(embedded[1]); check(dashboardData.locale, 'zh-CN'); check(dashboardData.meta.environmentLabel, '测试环境'); check(dashboardData.meta.platformLabel, '鸿蒙'); check(dashboardData.meta.generationLabel.startsWith('地图版本 '), true); check(dashboardData.meta.generationLabel.includes('snapshot-'), false); check(dashboardData.meta.snapshotStatusLabel, '部分可用'); check(dashboardData.overview.edges, snapshotGraph.edges.length); check(dashboardData.contexts[0].logicalGraph.nodes.some(x => x.kind === 'modal' && x.kindLabel === '业务弹窗'), true); check(dashboardData.contexts[0].reachableGraph.edges.some(x => x.evidence.before?.screenshotUrl.startsWith('../runs/')), true); check(dashboardData.contexts[0].reachableGraph.edges.every(x => x.replayabilityLabel === '不稳定'), true); check(dashboardData.contexts[0].reachableGraph.edges.some(x => x.label.startsWith('点击')), true);
  const firstDashboardSha = sha(dashboard.dashboardPath); run('build-dashboard.js', ['--app-map-root', root]); check(sha(dashboard.dashboardPath), firstDashboardSha);
  const pointerFile = path.join(root, 'snapshots', 'current.json'); const validPointer = JSON.parse(fs.readFileSync(pointerFile, 'utf8')); fs.writeFileSync(pointerFile, `${JSON.stringify({ ...validPointer, manifestSha256: 'sha256:corrupted' }, null, 2)}\n`); check(run('build-dashboard.js', ['--app-map-root', root], true).status !== 0, true); check(sha(dashboard.dashboardPath), firstDashboardSha); fs.writeFileSync(pointerFile, `${JSON.stringify(validPointer, null, 2)}\n`);
  check(run('graph.js', ['record-edge', '--scan-dir', scanDir, '--context', 'guest'], true).status !== 0, true);

  fs.writeFileSync(stateFile, 'home'); const empty = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-empty', '--device', 'fake-device', '--contexts', 'guest']).json.scanDir; prepareContext(empty, 'guest'); check(run('finalize-scan.js', ['--scan-dir', empty, '--status', 'COMPLETED'], true).status !== 0, true);

  fs.writeFileSync(stateFile, 'goal'); const goalRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-goal', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const targetPng = path.join(temp, 'target.png'); fs.writeFileSync(targetPng, Buffer.from([137,80,78,71,13,10,26,10])); const invalidGoalRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-invalid-goal', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed']).json.scanDir; const invalidGoal = run('parse-goal.js', ['--scan-dir', invalidGoalRun, '--description', '非法路径预算', '--screenshot', targetPng, '--context', 'authenticated', '--max-verified-paths', '1.5', '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全'] })], true); check(invalidGoal.status !== 0 && invalidGoal.stderr.includes('GOAL_POLICY_INVALID'), true); const goal = run('parse-goal.js', ['--scan-dir', goalRun, '--description', '进入账号与安全页面', '--screenshot', targetPng, '--context', 'authenticated', '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全', '修改密码'] })]).json.goal;
  const goalObs = prepareContext(goalRun, 'authenticated'); const goalVisual = run('graph.js', ['upsert-visual', '--scan-dir', goalRun, '--context', 'authenticated', '--root', 'true', '--observation-id', goalObs, '--logical-screen-key', 'account-security', '--name', '账号与安全']).json.visualState.id;
  const goalState = run('graph.js', ['upsert-reachable', '--scan-dir', goalRun, '--context', 'authenticated', '--root', 'true', '--visual-state-id', goalVisual, '--arrival-signature', '{}', '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  const assessment = JSON.stringify({ status: 'STRONG', referenceSha256: goal.referenceScreenshotSha256, observedSha256: sha(path.join(goalRun, 'evidence', 'observations', goalObs, 'screenshot.png')), rationale: 'visual match' });
  const evaluated = run('evaluate-goal.js', ['evaluate', '--scan-dir', goalRun, '--observation-id', goalObs, '--reachable-state-id', goalState, '--visual-assessment', assessment]).json; check(evaluated.runStatus, 'PAUSED');
  run('evaluate-goal.js', ['decide', '--scan-dir', goalRun, '--decision-id', evaluated.decision.decisionId, '--human-decision', 'CONFIRMED_TARGET']);
  const pending = run('verify-goal-path.js', ['prepare', '--scan-dir', goalRun, '--decision-id', evaluated.decision.decisionId]).json.pending; check(pending.status, 'AWAITING_VISUAL_ASSESSMENT');
  const replayAssessment = JSON.stringify({ status: 'STRONG', referenceSha256: goal.referenceScreenshotSha256, observedSha256: sha(path.join(goalRun, 'evidence', 'observations', pending.replayObservationId, 'screenshot.png')), rationale: 'replay visual match' });
  const verified = run('verify-goal-path.js', ['confirm', '--scan-dir', goalRun, '--visual-assessment', replayAssessment]).json; check(verified.goalResult.status, 'FOUND_VERIFIED');
  run('finalize-scan.js', ['--scan-dir', goalRun, '--status', 'COMPLETED']); check(fs.existsSync(path.join(goalRun, 'goal', 'verified-paths.json')), true);
  const legacyScanFile = path.join(scanDir, 'scan.json'); const legacyScan = JSON.parse(fs.readFileSync(legacyScanFile, 'utf8')); legacyScan.graphProtocolVersion = 1; fs.writeFileSync(legacyScanFile, `${JSON.stringify(legacyScan, null, 2)}\n`);
  const legacyGraphFile = path.join(scanDir, 'contexts', 'guest', 'graph.json'); const legacyGraph = JSON.parse(fs.readFileSync(legacyGraphFile, 'utf8')); const legacyEdge = legacyGraph.edges[0]; const waitAction = { type: 'wait', durationMs: 500 }; legacyEdge.action = waitAction; fs.writeFileSync(legacyGraphFile, `${JSON.stringify(legacyGraph, null, 2)}\n`);
  const legacyAttemptFile = path.join(scanDir, 'attempts', `${legacyEdge.attemptId}.json`); const legacyAttempt = JSON.parse(fs.readFileSync(legacyAttemptFile, 'utf8')); legacyAttempt.candidate = waitAction; legacyAttempt.candidateHash = hashObject(waitAction); fs.writeFileSync(legacyAttemptFile, `${JSON.stringify(legacyAttempt, null, 2)}\n`);
  const legacyActionFile = path.join(scanDir, 'evidence', 'actions', `${legacyEdge.evidence.actionResultId}.json`); const legacyAction = JSON.parse(fs.readFileSync(legacyActionFile, 'utf8')); legacyAction.action = waitAction; fs.writeFileSync(legacyActionFile, `${JSON.stringify(legacyAction, null, 2)}\n`);
  const legacyFrontierFile = path.join(scanDir, 'contexts', 'guest', 'frontier.json'); const legacyFrontier = JSON.parse(fs.readFileSync(legacyFrontierFile, 'utf8')); const legacyFrontierItem = legacyFrontier.items.find(item => item.id === legacyAttempt.frontierId); legacyFrontierItem.candidate = waitAction; fs.writeFileSync(legacyFrontierFile, `${JSON.stringify(legacyFrontier, null, 2)}\n`);
  let dashboardRejectedLegacy = false; try { assertConsumableGraph(legacyGraph, fail); } catch (error) { dashboardRejectedLegacy = error.code === 'CONSUMER_GRAPH_INVALID'; } check(dashboardRejectedLegacy, true);
  const normalizedSnapshot = run('build-snapshot.js', ['--app-map-root', root]).json; const normalizedMap = JSON.parse(fs.readFileSync(path.join(normalizedSnapshot.snapshotDir, 'map.json'), 'utf8')); const normalizedUnresolved = JSON.parse(fs.readFileSync(path.join(normalizedSnapshot.snapshotDir, 'unresolved.json'), 'utf8')); const normalizedMetrics = JSON.parse(fs.readFileSync(path.join(normalizedSnapshot.snapshotDir, 'metrics.json'), 'utf8')); check(normalizedMap.contexts.guest.edges.some(edge => edge.action?.type === 'wait'), false); check(normalizedUnresolved.items.some(item => item.type === 'LEGACY_NON_GRAPH_ACTION_DROPPED'), true); check(normalizedUnresolved.items.some(item => item.type === 'LEGACY_REACHABILITY_PRUNED'), true); check(normalizedMetrics.normalization.droppedWaitEdges >= 1, true);
  const normalizedDashboard = run('build-dashboard.js', ['--app-map-root', root]).json; const normalizedHtml = fs.readFileSync(normalizedDashboard.dashboardPath, 'utf8'); const normalizedEmbedded = normalizedHtml.match(/<script id="dashboard-data" type="application\/json">([\s\S]*?)<\/script>/); check(Boolean(normalizedEmbedded), true); const normalizedDashboardData = JSON.parse(normalizedEmbedded[1]); check(JSON.stringify(normalizedDashboardData).includes('"type":"wait"'), false); check(normalizedDashboardData.unresolved.some(item => item.type === 'LEGACY_NON_GRAPH_ACTION_DROPPED' && item.typeLabel === '已移除历史非路径动作'), true); check(normalizedDashboardData.unresolved.every(item => item.contextLabel === '未登录'), true);
  console.log(JSON.stringify({ schemaVersion: 1, ok: true, scope: 'full', tests, durationMs: Date.now() - suiteStartedMs, tempRoot: temp }, null, 2));
} finally { if (!process.env.SMAP_KEEP_SELF_TEST) fs.rmSync(temp, { recursive: true, force: true }); }
