#!/usr/bin/env node
'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { hashObject, fail, commitEvent, readJson } = require('./lib/common');
const { assertConsumableGraph } = require('./lib/graph-normalization');
const { actionLabel, localizeIssue } = require('./lib/dashboard-localization');
const { buildFingerprint, compareFingerprint } = require('./lib/fingerprint');
const { actionKey } = require('./lib/graph-store');
const { assessAction } = require('./lib/safety');
const { resolveSyntheticAction } = require('./lib/synthetic-data');

function requestedScope(argv = process.argv.slice(2)) {
  const index = argv.findIndex(value => value === '--scope');
  if (index >= 0) return argv[index + 1] || null;
  const inline = argv.find(value => value.startsWith('--scope='));
  return inline ? inline.slice('--scope='.length) : null;
}

const scope = requestedScope();
const help = process.argv.includes('--help') || process.argv.includes('-h');
if (help || !scope) {
  console.log(JSON.stringify({
    schemaVersion: 1,
    ok: help,
    code: help ? null : 'SELF_TEST_SCOPE_REQUIRED',
    message: '请选择自测范围；日常 Restore 修改优先运行轻量专项，完成后再显式运行一次全量自测。',
    commands: {
      restore: 'node scripts/self-test.js --scope restore',
      protocol: 'node scripts/self-test.js --scope protocol',
      scheduler: 'node scripts/self-test.js --scope scheduler',
      goalVerification: 'node scripts/self-test.js --scope goal-verification',
      sourceMatcher: 'node scripts/self-test.js --scope source-matcher',
      frontierCandidates: 'node scripts/self-test.js --scope frontier-candidates',
      flowExport: 'node scripts/self-test.js --scope flow-export',
      full: 'node scripts/self-test.js --scope full'
    }
  }, null, 2));
  process.exit(help ? 0 : 2);
}
if (scope === 'restore') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'restore-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'protocol') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'protocol-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'scheduler') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'scheduler-dependency-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'goal-verification') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'goal-verification-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'source-matcher') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'source-matcher-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'frontier-candidates') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'frontier-candidates-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope === 'flow-export') {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'flow-export-self-test.js')], { stdio: 'inherit' });
  process.exit(result.status == null ? 1 : result.status);
}
if (scope !== 'full') {
  console.error(JSON.stringify({ schemaVersion: 1, ok: false, error: { code: 'SELF_TEST_SCOPE_INVALID', message: `Unsupported self-test scope: ${scope}` } }));
  process.exit(2);
}
const suiteStartedMs = Date.now();
process.stderr.write('[SMAP] 正在运行全量自测；开发迭代请优先使用 --scope restore。\n');
{
  const result = spawnSync(process.execPath, [path.join(__dirname, 'scheduler-dependency-self-test.js')], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status == null ? 1 : result.status);
}
{
  const result = spawnSync(process.execPath, [path.join(__dirname, 'goal-verification-self-test.js')], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status == null ? 1 : result.status);
}
{
  const result = spawnSync(process.execPath, [path.join(__dirname, 'source-matcher-self-test.js')], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status == null ? 1 : result.status);
}
{
  const result = spawnSync(process.execPath, [path.join(__dirname, 'frontier-candidates-self-test.js')], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status == null ? 1 : result.status);
}
{
  const result = spawnSync(process.execPath, [path.join(__dirname, 'flow-export-self-test.js')], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status == null ? 1 : result.status);
}

const scripts = __dirname; const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'smap-self-test-')); const bin = path.join(temp, 'bin'); fs.mkdirSync(bin); const stateFile = path.join(temp, 'state'); const restartModeFile = path.join(temp, 'restart-mode'); const restartCountFile = path.join(temp, 'restart-count'); fs.writeFileSync(stateFile, 'home'); fs.writeFileSync(restartModeFile, ''); fs.writeFileSync(restartCountFile, '0');
const fakeHdc = `#!/usr/bin/env node
const fs=require('fs'); const a=process.argv.slice(2); const stateFile=process.env.SMAP_FAKE_STATE; const i=a[0]==='-t'?2:0; const c=a.slice(i);
if(c[0]==='shell'&&c[1]==='uitest'&&c[2]==='--version'){console.log('uitest 1.0');process.exit(0)}
if(c[0]==='shell'&&c[1]==='aa'&&c[2]==='dump'){console.log('AbilityRecord ID #1\\n state #FOREGROUND\\n ability type [PAGE]\\n bundle name [com.example.demo]\\n main name [EntryAbility]');process.exit(0)}
if(c[0]==='shell'&&c[1]==='uitest'&&c[2]==='uiInput'){if(c[3]==='click'){const x=Number(c[4]);const y=Number(c[5]);const s=fs.readFileSync(stateFile,'utf8').trim();if(s==='action-error')process.exit(2);if((s==='businessmodal'||s==='nuisance'||s==='startup-popup')&&(x>=300||y>=100))fs.writeFileSync(stateFile,s==='startup-popup'?'home':'profile');else if(s==='home'&&y>=100&&y<200)fs.writeFileSync(stateFile,'profile-render-1');else if(s==='home'&&y>=200)fs.writeFileSync(stateFile,'businessmodal');else if(s==='profile'&&y>=200&&y<300)fs.writeFileSync(stateFile,'businessmodal');else if(s==='profile'&&y>=300)fs.writeFileSync(stateFile,'nuisance');else if(x<100)fs.writeFileSync(stateFile,'profile-render-1');else if(x<200)fs.writeFileSync(stateFile,'businessmodal');else if(x<300)fs.writeFileSync(stateFile,'nuisance')}else if(c[3]==='keyEvent'&&String(c[4]).toUpperCase()==='BACK'){const s=fs.readFileSync(stateFile,'utf8').trim();if(s==='profile')fs.writeFileSync(stateFile,'home');else if(['businessmodal','nuisance'].includes(s))fs.writeFileSync(stateFile,'profile')}process.exit(0)}
if(c[0]==='shell'&&c[1]==='aa'){if(c[2]==='start'){const countFile=process.env.SMAP_FAKE_RESTART_COUNT;fs.writeFileSync(countFile,String(Number(fs.readFileSync(countFile,'utf8'))+1));const s=fs.readFileSync(stateFile,'utf8').trim();const mode=fs.readFileSync(process.env.SMAP_FAKE_RESTART_MODE,'utf8').trim();if(mode==='startup-popup')fs.writeFileSync(stateFile,'startup-popup');else if(mode!=='preserve'&&!['goal','startup-popup'].includes(s))fs.writeFileSync(stateFile,'home')}process.exit(0)}
if(c[0]==='shell'&&c[1]==='uitest'&&['screenCap','dumpLayout'].includes(c[2]))process.exit(0);
if(c[0]==='file'&&c[1]==='recv'){const out=c[3];fs.mkdirSync(require('path').dirname(out),{recursive:true});const s=fs.readFileSync(stateFile,'utf8').trim();if(c[2].endsWith('.png')){fs.writeFileSync(out,Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.from(s)]));if(s==='profile-render-1')fs.writeFileSync(stateFile,'profile-render-2');else if(s==='profile-render-2')fs.writeFileSync(stateFile,'profile');else if(s.startsWith('animated-'))fs.writeFileSync(stateFile,'animated-'+(Number(s.split('-')[1])+1))}else{const texts=s==='profile'?['我的','设置','筛选','活动入口']:s==='goal'?['账号与安全','修改密码']:s==='businessmodal'?['筛选条件','关闭']:s==='nuisance'?['活动提示','稍后']:s==='startup-popup'?['启动公告','关闭']:s==='loading'||s.startsWith('profile-render-')?['加载中']:['首页','我的','扩展弹窗'];fs.writeFileSync(out,JSON.stringify({type:s.includes('popup')||s.includes('modal')||s==='nuisance'?'Dialog':'Page',children:texts.map((text,n)=>({type:'Text',resourceId:'id'+n,text,bounds:[0,n*100,100,n*100+50]}))}))}process.exit(0)}
process.exit(0);`;
fs.writeFileSync(path.join(bin, 'hdc.js'), fakeHdc, { mode: 0o644 }); fs.writeFileSync(path.join(bin, 'hdc'), `#!/bin/sh\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(path.join(bin, 'hdc.js'))} "$@"\n`, { mode: 0o755 }); fs.writeFileSync(path.join(bin, 'devecocli.js'), 'console.log("fake-device connected")\n', { mode: 0o644 }); fs.writeFileSync(path.join(bin, 'devecocli'), `#!/bin/sh\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(path.join(bin, 'devecocli.js'))} "$@"\n`, { mode: 0o755 });
const env = { ...process.env, PATH: `${bin}:${process.env.PATH}`, SMAP_HDC: path.join(bin, 'hdc'), SMAP_DEVECOCLI: path.join(bin, 'devecocli'), SMAP_FAKE_STATE: stateFile, SMAP_FAKE_RESTART_MODE: restartModeFile, SMAP_FAKE_RESTART_COUNT: restartCountFile, SMAP_RESTART_SETTLE_MS: '1', SMAP_OBSERVATION_INITIAL_DELAY_MS: '0', SMAP_OBSERVATION_SAMPLE_INTERVAL_MS: '0', SMAP_OBSERVATION_TIMEOUT_MS: '1000', SMAP_OBSERVATION_VISUAL_FALLBACK_MS: '0' };
	function visualAssessment(pageName = '自测页面') { return JSON.stringify({ status: 'ACCEPTED', pageUsable: true, pageKind: 'page', pageName, confidence: 'HIGH', rationale: 'self-test accepted visual evidence' }); }
	function argValue(args, name) { const index = args.indexOf(name); return index >= 0 ? args[index + 1] : null; }
	function run(file, args = [], allowFailure = false) {
	  let actualArgs = [...args];
	  if (file === 'graph.js' && actualArgs[0] === 'upsert-visual' && !actualArgs.includes('--visual-review-id')) {
	    const scanDir = argValue(actualArgs, '--scan-dir'); const contextId = argValue(actualArgs, '--context') || 'guest'; const observationId = argValue(actualArgs, '--observation-id'); const name = argValue(actualArgs, '--name') || argValue(actualArgs, '--logical-screen-key') || '根页面';
	    const review = run('visual-review.js', ['record', '--scan-dir', scanDir, '--context', contextId, '--observation-id', observationId, '--review-type', 'ROOT_STATE', '--assessment', visualAssessment(name)]).json.visualReview;
	    actualArgs = [...actualArgs, '--visual-review-id', review.visualReviewId];
	  }
	  const command = file.endsWith('.js') ? process.execPath : path.join(scripts, file); const commandArgs = file.endsWith('.js') ? [path.join(scripts, file), ...actualArgs] : actualArgs; const result = spawnSync(command, commandArgs, { encoding: 'utf8', env, timeout: 60000 }); if (!allowFailure && result.status !== 0) throw new Error(`${file} failed (${result.status}, signal=${result.signal}, error=${result.error?.code || 'none'}): ${result.stderr}\n${result.stdout}`); let json = null; try { json = JSON.parse(result.stdout); } catch {}
	  if (!allowFailure && file === 'execute-frontier.js' && result.status === 0 && json?.attempt?.status === 'AWAITING_VISUAL_REVIEW') {
	    const scanDir = argValue(actualArgs, '--scan-dir'); const contextId = argValue(actualArgs, '--context') || 'guest'; const attempt = json.attempt;
	    const accepted = run('visual-review.js', ['record', '--scan-dir', scanDir, '--context', contextId, '--attempt-id', attempt.attemptId, '--observation-id', attempt.reviewObservationId, '--review-type', 'PAGE_OUTCOME', '--assessment', visualAssessment('动作结果')]).json;
	    json = { ...json, attempt: accepted.attempt, visualReview: accepted.visualReview };
	  }
	  return { ...result, json };
	}
function sha(file) { return `sha256:${crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}`; }
function prepareContext(scanDir, contextId) { const shown = run('show-plan.js', ['--scan-dir', scanDir]).json; run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', shown.planHash]); const prepared = run('prepare-context.js', ['--scan-dir', scanDir, '--context', contextId]).json; const obs = prepared.observation.observationId; run('context.js', ['verify', '--scan-dir', scanDir, '--context', contextId, '--observation-id', obs]); run('context.js', ['start', '--scan-dir', scanDir, '--context', contextId]); return obs; }

let tests = 0; function check(value, expected) { assert.deepEqual(value, expected); tests += 1; }
try {
  check(actionLabel({ type: 'tap', target: '我的' }), '点击 · 我的'); check(actionLabel({ type: 'keyEvent', key: 'BACK' }), '按键 · 返回键'); check(localizeIssue({ type: 'EDGE_ENDPOINT_UNRESOLVED', contextId: 'guest', runId: 'run-1', sourceEdgeId: 'edge-1' }).typeLabel, '跳转端点无法解析');
  const fingerprintLayout = { type: 'Page', children: [{ type: 'Text', text: '相同布局' }] }; check(compareFingerprint(buildFingerprint(fingerprintLayout, { bundleName: 'demo', ability: 'Entry' }, { screenshotSha256: 'sha256:a' }), buildFingerprint(fingerprintLayout, { bundleName: 'demo', ability: 'Entry' }, { screenshotSha256: 'sha256:b' })), 'PROBABLE');
  check(actionKey({ type: 'tap', x: 10, y: 10 }) === actionKey({ type: 'tap', x: 900, y: 900 }), true);
  check(assessAction({ type: 'inputText', value: 'fixed' }, { environment: 'test' }).replayPolicy, 'NONREPEATABLE'); const syntheticAction = { type: 'inputText', value: '', syntheticSpec: { type: 'email', prefix: 'smap' } }; check(assessAction(syntheticAction, { environment: 'test' }).replayPolicy, 'REGENERATE_SYNTHETIC'); check(resolveSyntheticAction(syntheticAction, 'one').value === resolveSyntheticAction(syntheticAction, 'two').value, false);
  check(run('probe-env.sh', ['--device', 'fake-device']).json.ok, true);
  const root = path.join(temp, 'app-map'); run('init-app-root.js', ['--app-map-root', root, '--bundle-name', 'com.example.demo', '--entry-ability', 'EntryAbility', '--environment', 'test']);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', '../escape', '--device', 'fake-device'], true).status !== 0, true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-module', '--device', 'fake-device', '--scan-scope', 'module'], true).status !== 0, true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-wrong-profile', '--device', 'fake-device', '--profile', 'goal'], true).stderr.includes('PROFILE_MODE_MISMATCH'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-multi-context', '--device', 'fake-device', '--contexts', 'guest,authenticated'], true).stderr.includes('CONTEXT_INVALID'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-bad-navigation', '--device', 'fake-device', '--navigation-policy', 'unknown'], true).stderr.includes('NAVIGATION_POLICY_INVALID'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-internal-budget', '--device', 'fake-device', '--budget', JSON.stringify({ maxDeviceActions: 1 })], true).stderr.includes('BUDGET_FIELD_INTERNAL'), true);
  const preview = run('preview-plan.js', ['--app-map-root', root, '--scan-id', 'scan-preview-confirmed', '--device', 'fake-device', '--context', 'guest', '--profile', 'standard']).json; check(preview.createsRunDirectory, false); check(fs.existsSync(path.join(root, 'runs', 'scan-preview-confirmed')), false); check(fs.existsSync(path.join(root, 'maps', 'guest', 'graph.json')), false); check(preview.planHash.startsWith('sha256:'), true);
  check(run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-preview-bad-hash', '--device', 'fake-device', '--context', 'guest', '--confirmed-plan-hash', 'sha256:stale'], true).stderr.includes('PLAN_HASH_MISMATCH'), true); check(fs.existsSync(path.join(root, 'runs', 'scan-preview-bad-hash')), false);
  const confirmedPreviewRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-preview-confirmed', '--device', 'fake-device', '--context', 'guest', '--profile', 'standard', '--confirmed-plan-hash', preview.planHash]).json; check(confirmedPreviewRun.scan.status, 'PLAN_CONFIRMED'); check(JSON.parse(fs.readFileSync(path.join(confirmedPreviewRun.scanDir, 'plan.json'), 'utf8')).planHash, preview.planHash); check(run('show-plan.js', ['--scan-dir', confirmedPreviewRun.scanDir], true).stderr.includes('RUN_STATE_INVALID'), true);
  fs.writeFileSync(stateFile, 'home'); const budgetRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-budget-exhaustion', '--device', 'fake-device', '--context', 'guest', '--profile', 'quick']).json.scanDir; prepareContext(budgetRun, 'guest'); const budgetMetricsPath = path.join(budgetRun, 'contexts', 'guest', 'metrics.json'); const budgetMetrics = readJson(budgetMetricsPath); budgetMetrics.activeDurationMs = 10 * 60 * 1000 + 1000; budgetMetrics.activeStartedAt = new Date(Date.now() - 1000).toISOString(); commitEvent(budgetRun, 'faultInjectionBudgetExhausted', { contextId: 'guest' }, [{ path: 'contexts/guest/metrics.json', op: 'REPLACE', value: budgetMetrics }]);
  const budgetStop = run('next-work.js', ['--scan-dir', budgetRun, '--context', 'guest']).json; check(budgetStop.decision, 'STOP'); check(budgetStop.reasonCode, 'MAX_ACTIVE_MINUTES'); check(budgetStop.suggestedTerminalStatus, 'PARTIAL'); check(run('finalize-scan.js', ['--scan-dir', budgetRun, '--status', 'COMPLETED'], true).status !== 0, true); check(Boolean(readJson(budgetMetricsPath).activeStartedAt), true); check(readJson(path.join(budgetRun, 'scan.json')).status, 'SCANNING'); check(run('finalize-scan.js', ['--scan-dir', budgetRun, '--status', 'PARTIAL']).json.scan.status, 'PARTIAL'); check(readJson(budgetMetricsPath).activeStartedAt, null); fs.rmSync(budgetRun, { recursive: true, force: true });
  const scanDir = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-exploration', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const displayedPlan = run('show-plan.js', ['--scan-dir', scanDir]).json; check(displayedPlan.plan.schemaVersion, 3); check(displayedPlan.plan.profileSelection.availableProfiles.length, 4); check(displayedPlan.plan.profileSelection.selectedProfile, 'standard'); check(displayedPlan.plan.profileSelection.availableProfiles.find(item => item.id === 'quick').budget.maxActiveMinutes, 10); check(displayedPlan.plan.profileSelection.availableProfiles.find(item => item.id === 'goal').applicable, false); check(displayedPlan.plan.context.id, 'guest'); check(displayedPlan.plan.userConfiguration.maxActiveMinutes, 20); check(displayedPlan.plan.execution.verificationRule, 'CANONICAL_SCREEN_PATH'); check(displayedPlan.plan.timeExpectation.wallClockGuarantee, false); check(run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', 'sha256:stale'], true).status !== 0, true);
  const configuredPlan = run('context.js', ['configure-plan', '--scan-dir', scanDir, '--profile', 'deep', '--budget', JSON.stringify({ maxActiveMinutes: 30 })]).json; check(configuredPlan.plan.profileSelection.selectedProfile, 'deep'); check(configuredPlan.plan.profileSelection.hasBudgetOverrides, true); check(configuredPlan.plan.derivedExecutionLimits.maxActiveMinutes, 30); check(configuredPlan.plan.profileSelection.budgetOverrides[0].actualValue, 30); check(run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', displayedPlan.planHash], true).stderr.includes('PLAN_HASH_MISMATCH'), true); const refreshedPlan = run('show-plan.js', ['--scan-dir', scanDir]).json; check(refreshedPlan.planHash, configuredPlan.planHash);
  run('context.js', ['confirm-plan', '--scan-dir', scanDir, '--plan-hash', configuredPlan.planHash]); check(run('context.js', ['configure-plan', '--scan-dir', scanDir, '--profile', 'quick'], true).stderr.includes('RUN_STATE_INVALID'), true); fs.writeFileSync(stateFile, 'startup-popup');
  const prepared = run('prepare-context.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest']).json; check(fs.readFileSync(stateFile, 'utf8'), 'startup-popup'); check(prepared.requiresIdentityConfirmation, undefined);
  const stableCheck = run('prepare-context.js', ['observe-again', '--scan-dir', scanDir, '--context', 'guest', '--preparation-id', prepared.preparation.preparationId, '--observation-id', prepared.observation.observationId]).json; check(stableCheck.preparation.stabilityChecks.length, 1);
  const cleaned = run('prepare-context.js', ['dismiss-popup', '--scan-dir', scanDir, '--context', 'guest', '--preparation-id', stableCheck.preparation.preparationId, '--observation-id', stableCheck.observation.observationId, '--dismiss-action', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json; check(fs.readFileSync(stateFile, 'utf8'), 'home'); check(cleaned.preparation.interruptions.length, 1);
  const preflight = cleaned.observation.observationId; run('context.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--observation-id', preflight]); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']); run('context.js', ['pause', '--scan-dir', scanDir, '--reason-code', 'TEST_HUMAN_WAIT']); const pausedDuration = JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')).activeDurationMs; Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 20); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')).activeDurationMs, pausedDuration); check(run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'context-verification'], true).status !== 0, true); fs.writeFileSync(stateFile, 'loading'); check(run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'scan'], true).status !== 0, true); check(fs.readdirSync(path.join(scanDir, 'evidence', 'logs')).some(name => name.endsWith('-stability-timeout.json')), true); fs.writeFileSync(stateFile, 'animated-1'); const dynamicObservation = run('observe.sh', ['--scan-dir', scanDir, '--context', 'guest', '--purpose', 'scan']).json.observation; check(dynamicObservation.stability.status, 'LAYOUT_STABLE_VISUAL_VARIANCE'); check(dynamicObservation.stability.sampleCount, 3); fs.writeFileSync(stateFile, 'home'); const visual1 = run('graph.js', ['upsert-visual', '--scan-dir', scanDir, '--context', 'guest', '--root', 'true', '--observation-id', preflight, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id;
  const rootState = run('graph.js', ['upsert-reachable', '--scan-dir', scanDir, '--context', 'guest', '--root', 'true', '--visual-state-id', visual1, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  fs.writeFileSync(restartModeFile, 'startup-popup'); const recurringFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'home/recurring-startup-popup', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item; const recurringClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; const restartsBeforeRecurringRestore = Number(fs.readFileSync(restartCountFile, 'utf8')); let recurringAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', recurringFrontier.id, '--claim-token', recurringClaim.claimToken]).json.attempt; check(recurringAttempt.status, 'AWAITING_RESTORE_REVIEW'); const restartsAfterRecurringRestore = Number(fs.readFileSync(restartCountFile, 'utf8')); check(restartsAfterRecurringRestore, restartsBeforeRecurringRestore + 1); const legacyRestoreFile = path.join(scanDir, 'evidence', 'restores', `${recurringAttempt.activeRestoreId}.json`); const legacyRestore = JSON.parse(fs.readFileSync(legacyRestoreFile, 'utf8')); legacyRestore.schemaVersion = 1; delete legacyRestore.checkpoint; fs.writeFileSync(legacyRestoreFile, `${JSON.stringify(legacyRestore, null, 2)}\n`); const recurringReview = run('execute-frontier.js', ['review-restore', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId, '--observation-id', recurringAttempt.reviewObservationId, '--disposition', 'DISMISSIBLE_POPUP', '--dismiss-action', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json; recurringAttempt = recurringReview.attempt; check(recurringAttempt.status, 'READY_FOR_ACTION'); check(Number(fs.readFileSync(restartCountFile, 'utf8')), restartsAfterRecurringRestore); check(recurringAttempt.interruptions[0].afterObservationId != null, true); check(recurringAttempt.restoreResults.length, 1); check(recurringAttempt.restoreResults[0].status, 'SUCCEEDED'); recurringAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId]).json.attempt; const recurringResolved = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', recurringAttempt.attemptId, '--observation-id', recurringAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json; check(recurringResolved.attempt.status, 'NO_STATE_CHANGE'); fs.writeFileSync(restartModeFile, '');
  check(run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'internal/wait', '--candidate', JSON.stringify({ type: 'wait', durationMs: 500 })], true).status !== 0, true);
  const noChangeFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'home/no-op', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item; const noChangeClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(noChangeClaim.id, noChangeFrontier.id);
  let noChangeAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', noChangeFrontier.id, '--claim-token', noChangeClaim.claimToken]).json.attempt; noChangeAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId]).json.attempt; check(noChangeAttempt.sourceComparison, 'EXACT'); check(run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId, '--observation-id', noChangeAttempt.reviewObservationId, '--disposition', 'PAGE'], true).status !== 0, true); const noChangeReview = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', noChangeAttempt.attemptId, '--observation-id', noChangeAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json; check(noChangeReview.edgeCreated, false); check(noChangeReview.attempt.status, 'NO_STATE_CHANGE'); check(noChangeReview.frontier.reasonCode, 'NO_STATE_CHANGE'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'graph.json'), 'utf8')).edges.length, 0);
  const frontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', rootState, '--candidate-group-key', 'bottom/profile', '--candidate', JSON.stringify({ type: 'tap', target: '我的', fallbackBounds: [0, 0, 100, 100], routeTransition: true })]).json.item;
  const profileClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(profileClaim.id, frontier.id);
  let attempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', frontier.id, '--claim-token', profileClaim.claimToken]).json.attempt; check(attempt.status, 'READY_FOR_ACTION'); const duplicatePrepare = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', frontier.id, '--claim-token', profileClaim.claimToken]).json; check(duplicatePrepare.reused, true); check(duplicatePrepare.attempt.attemptId, attempt.attemptId);
  attempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId]).json.attempt; check(attempt.status, 'AWAITING_OUTCOME_REVIEW'); const stabilizedActionObservation = JSON.parse(fs.readFileSync(path.join(scanDir, 'evidence', 'observations', attempt.reviewObservationId, 'observation.json'), 'utf8')); check(stabilizedActionObservation.stability.status, 'STABLE'); check(stabilizedActionObservation.stability.sampleCount >= 4, true); check(stabilizedActionObservation.trigger, 'ACTION');
  attempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId, '--observation-id', attempt.reviewObservationId, '--disposition', 'TRANSIENT']).json.attempt; check(attempt.stabilityChecks.length, 1);
  attempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', attempt.attemptId, '--observation-id', attempt.reviewObservationId, '--disposition', 'PAGE']).json.attempt; check(attempt.status, 'READY_TO_COMMIT');
  const committed = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', attempt.attemptId, '--logical-screen-key', 'profile', '--name', '我的']).json; check(committed.attempt.status, 'COMMITTED'); check(committed.edge.attemptId, attempt.attemptId); check(committed.edge.replayability, 'STABLE'); check(run('next-work.js', ['--scan-dir', scanDir, '--context', 'guest']).json.decision, 'VERIFY');
  const backVerified = run('back-capability.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--to-reachable-state-id', rootState]).json; check(backVerified.backCapability.verificationStatus, 'EXACT'); check(fs.readFileSync(stateFile, 'utf8'), 'home'); check(run('back-capability.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.length, 1);
  const committedGraphFile = path.join(scanDir, 'contexts', 'guest', 'graph.json'); const damagedGraph = JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')); damagedGraph.edges = []; damagedGraph.reachableStates = damagedGraph.reachableStates.filter(x => x.id !== committed.reachableState.id); damagedGraph.visualStates = damagedGraph.visualStates.filter(x => x.id !== committed.visualState.id); damagedGraph.logicalScreens = damagedGraph.logicalScreens.filter(x => x.id !== 'profile'); fs.writeFileSync(committedGraphFile, `${JSON.stringify(damagedGraph, null, 2)}\n`); run('context.js', ['pause', '--scan-dir', scanDir, '--reason-code', 'TEST_RECOVERY']); const recoveredGraph = JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')); check(recoveredGraph.edges.some(x => x.id === committed.edge.id), true); check(recoveredGraph.reachableStates.some(x => x.id === committed.reachableState.id), true); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']);
  const modalFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/filter', '--candidate', JSON.stringify({ type: 'tap', target: '筛选', fallbackBounds: [100, 0, 200, 100] })]).json.item; const modalClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(modalClaim.id, modalFrontier.id);
  let modalAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', modalFrontier.id, '--claim-token', modalClaim.claimToken]).json.attempt; modalAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', modalAttempt.attemptId]).json.attempt; modalAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', modalAttempt.attemptId, '--observation-id', modalAttempt.reviewObservationId, '--disposition', 'BUSINESS_MODAL']).json.attempt;
  const modalCommitted = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', modalAttempt.attemptId, '--logical-screen-key', 'profile-filter', '--name', '筛选条件']).json; check(modalCommitted.visualState.kind, 'modal'); check(modalCommitted.reachableState.depth.modalDepth, 1);
  const closeFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', modalCommitted.reachableState.id, '--candidate-group-key', 'filter/close', '--candidate', JSON.stringify({ type: 'tap', target: '关闭', fallbackBounds: [300, 0, 400, 100] })]).json.item; const closeClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(closeClaim.id, closeFrontier.id);
  let closeAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', closeFrontier.id, '--claim-token', closeClaim.claimToken]).json.attempt; closeAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', closeAttempt.attemptId]).json.attempt; closeAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', closeAttempt.attemptId, '--observation-id', closeAttempt.reviewObservationId, '--disposition', 'PAGE']).json.attempt;
  const logicalConflict = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', closeAttempt.attemptId, '--logical-screen-key', 'profile-alias', '--name', '我的别名'], true); check(logicalConflict.status !== 0 && logicalConflict.stderr.includes('LOGICAL_SCREEN_CONFLICT'), true); check(JSON.parse(fs.readFileSync(committedGraphFile, 'utf8')).logicalScreens.some(x => x.id === 'profile-alias'), false); const closeCommitted = run('commit-attempt.js', ['--scan-dir', scanDir, '--attempt-id', closeAttempt.attemptId, '--logical-screen-key', 'profile', '--name', '我的']).json; check(closeCommitted.reachableState.depth.modalDepth, 0);
  const nuisanceFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/activity-tip', '--candidate', JSON.stringify({ type: 'tap', target: '活动入口', fallbackBounds: [200, 0, 300, 100] })]).json.item; const nuisanceClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; check(nuisanceClaim.id, nuisanceFrontier.id);
  let nuisanceAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', nuisanceFrontier.id, '--claim-token', nuisanceClaim.claimToken]).json.attempt; nuisanceAttempt = run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', nuisanceAttempt.attemptId]).json.attempt;
  const nuisanceReviewed = run('execute-frontier.js', ['review-outcome', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', nuisanceAttempt.attemptId, '--observation-id', nuisanceAttempt.reviewObservationId, '--disposition', 'DISMISSIBLE_POPUP', '--dismiss-action', JSON.stringify({ type: 'tap', target: '稍后', fallbackBounds: [300, 0, 400, 100] })]).json; check(nuisanceReviewed.edgeCreated, false); check(nuisanceReviewed.attempt.status, 'DISMISSED_NO_EDGE'); check(fs.readFileSync(stateFile, 'utf8'), 'profile');
  const failureFrontier = run('frontier.js', ['add', '--scan-dir', scanDir, '--context', 'guest', '--from-reachable-state-id', committed.reachableState.id, '--candidate-group-key', 'profile/failure-recovery', '--candidate', JSON.stringify({ type: 'tap', target: '故障恢复测试', fallbackBounds: [400, 0, 500, 100] })]).json.item; const failureClaim = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json.item; const failureAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest', '--frontier-id', failureFrontier.id, '--claim-token', failureClaim.claimToken]).json.attempt;
  fs.writeFileSync(stateFile, 'action-error'); check(run('execute-frontier.js', ['act', '--scan-dir', scanDir, '--context', 'guest', '--attempt-id', failureAttempt.attemptId], true).status !== 0, true); fs.writeFileSync(stateFile, 'profile'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'scan.json'), 'utf8')).status, 'PAUSED'); check(JSON.parse(fs.readFileSync(path.join(scanDir, 'attempts', `${failureAttempt.attemptId}.json`), 'utf8')).status, 'UNKNOWN_EFFECT');
  const unknownOperation = run('operation.js', ['list', '--scan-dir', scanDir]).json.items.find(item => item.owner?.type === 'ATTEMPT' && item.owner.id === failureAttempt.attemptId && item.status === 'UNKNOWN_OUTCOME'); check(Boolean(unknownOperation), true);
  const recoveryPreparation = run('prepare-context.js', ['prepare', '--scan-dir', scanDir, '--context', 'guest']).json; const recoveryObservationId = recoveryPreparation.observation.observationId; run('operation.js', ['reconcile', '--scan-dir', scanDir, '--operation-id', unknownOperation.operationId, '--resolution', 'NO_EFFECT', '--observation-id', recoveryObservationId]);
  const retryableFailure = run('frontier.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.find(x => x.id === failureFrontier.id); check(retryableFailure.status, 'RETRYABLE'); check(retryableFailure.claimedAttemptId, null); run('context.js', ['verify', '--scan-dir', scanDir, '--context', 'guest', '--observation-id', recoveryObservationId]); run('context.js', ['start', '--scan-dir', scanDir, '--context', 'guest']);
  let retryClaimResult = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json; while (retryClaimResult.decision === 'VERIFY') { run('verify-path.js', ['run', '--scan-dir', scanDir, '--context', 'guest', '--verification-id', retryClaimResult.verification.verificationId]); retryClaimResult = run('frontier.js', ['claim', '--scan-dir', scanDir, '--context', 'guest']).json; } const retryClaim = retryClaimResult.item; run('frontier.js', ['resolve', '--scan-dir', scanDir, '--context', 'guest', '--id', retryClaim.id, '--status', 'FAILED', '--reason-code', 'TEST_FAILURE_RESOLVED']);
  fs.writeFileSync(restartModeFile, ''); for (const verification of run('verify-path.js', ['list', '--scan-dir', scanDir, '--context', 'guest']).json.items.filter(item => item.status === 'PENDING')) run('verify-path.js', ['run', '--scan-dir', scanDir, '--context', 'guest', '--verification-id', verification.verificationId]);
  run('finalize-scan.js', ['--scan-dir', scanDir, '--status', 'COMPLETED']); const finalizedMetrics = JSON.parse(fs.readFileSync(path.join(scanDir, 'contexts', 'guest', 'metrics.json'), 'utf8')); check(finalizedMetrics.observationSamples > finalizedMetrics.observations, true); check(finalizedMetrics.observationStabilityWaitMs >= 0, true); check(finalizedMetrics.noStateChangeActions, 2); check(finalizedMetrics.verificationActions > 0, true); check(fs.readFileSync(path.join(scanDir, 'report.md'), 'utf8').includes('观测稳定性'), true); run('register-run.js', ['--scan-dir', scanDir]);
  fs.writeFileSync(stateFile, 'animated-1'); fs.writeFileSync(restartModeFile, 'preserve');
  const dynamicRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-dynamic-restore', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const dynamicRootObservationId = prepareContext(dynamicRun, 'guest'); const dynamicRootObservation = JSON.parse(fs.readFileSync(path.join(dynamicRun, 'evidence', 'observations', dynamicRootObservationId, 'observation.json'), 'utf8')); check(dynamicRootObservation.stability.status, 'LAYOUT_STABLE_VISUAL_VARIANCE');
  const dynamicRootVisual = run('graph.js', ['upsert-visual', '--scan-dir', dynamicRun, '--context', 'guest', '--root', 'true', '--observation-id', dynamicRootObservationId, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id;
  const dynamicRootState = run('graph.js', ['upsert-reachable', '--scan-dir', dynamicRun, '--context', 'guest', '--root', 'true', '--visual-state-id', dynamicRootVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  fs.writeFileSync(restartModeFile, ''); fs.writeFileSync(stateFile, 'home');
  const dynamicFrontier = run('frontier.js', ['add', '--scan-dir', dynamicRun, '--context', 'guest', '--from-reachable-state-id', dynamicRootState, '--candidate-group-key', 'home/dynamic-restore', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item;
  const dynamicClaim = run('frontier.js', ['claim', '--scan-dir', dynamicRun, '--context', 'guest']).json.item;
  const dynamicPrepared = run('execute-frontier.js', ['prepare', '--scan-dir', dynamicRun, '--context', 'guest', '--frontier-id', dynamicFrontier.id, '--claim-token', dynamicClaim.claimToken]).json; let dynamicAttempt = dynamicPrepared.attempt; check(dynamicAttempt.status, 'READY_FOR_ACTION'); check(dynamicPrepared.reviewRequest, undefined); check(dynamicAttempt.restoreResults[0].equivalenceReviews.length, 0); check(readJson(path.join(dynamicRun, 'contexts', 'guest', 'visual-equivalence.json')).rules.length, 0); check(readJson(path.join(dynamicRun, 'contexts', 'guest', 'state-equivalence.json')).rules.length, 0);
  dynamicAttempt = run('execute-frontier.js', ['act', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId]).json.attempt;
  const dynamicResolved = run('execute-frontier.js', ['review-outcome', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId, '--observation-id', dynamicAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json;
  check(dynamicResolved.attempt.status, 'NO_STATE_CHANGE'); const dynamicCachedFrontier = run('frontier.js', ['add', '--scan-dir', dynamicRun, '--context', 'guest', '--from-reachable-state-id', dynamicRootState, '--candidate-group-key', 'home/dynamic-restore-cached', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域2', fallbackBounds: [400, 0, 500, 100] })]).json.item; const dynamicCachedClaim = run('frontier.js', ['claim', '--scan-dir', dynamicRun, '--context', 'guest']).json.item; const dynamicCachedPrepared = run('execute-frontier.js', ['prepare', '--scan-dir', dynamicRun, '--context', 'guest', '--frontier-id', dynamicCachedFrontier.id, '--claim-token', dynamicCachedClaim.claimToken]).json; check(dynamicCachedPrepared.attempt.status, 'READY_FOR_ACTION'); check(dynamicCachedPrepared.reviewRequest, undefined); check(dynamicCachedPrepared.attempt.restoreResults.at(-1).equivalenceReviews.length, 0); check(run('execute-frontier.js', ['act', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', 'undefined'], true).stderr.includes('ATTEMPT_ID_INVALID'), true);
  dynamicAttempt = run('execute-frontier.js', ['act', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicCachedPrepared.attemptId]).json.attempt; const dynamicCachedResolved = run('execute-frontier.js', ['review-outcome', '--scan-dir', dynamicRun, '--context', 'guest', '--attempt-id', dynamicAttempt.attemptId, '--observation-id', dynamicAttempt.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']).json; check(dynamicCachedResolved.attempt.status, 'NO_STATE_CHANGE'); check(run('finalize-scan.js', ['--scan-dir', dynamicRun, '--status', 'COMPLETED']).json.scan.status, 'COMPLETED'); const dynamicRebuilt = run('rebuild-run.js', ['--scan-dir', dynamicRun, '--output-dir', path.join(temp, 'rebuilt-dynamic')]).json; check(dynamicRebuilt.ok, true); check(dynamicRebuilt.comparisons['contexts/guest/visual-equivalence.json'].equivalent, true); check(dynamicRebuilt.comparisons['contexts/guest/state-equivalence.json'].equivalent, true); fs.rmSync(dynamicRun, { recursive: true, force: true });
  fs.writeFileSync(stateFile, 'home'); fs.writeFileSync(restartModeFile, ''); const nonDynamicRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-nondynamic-equivalence', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir; const nonDynamicObs = prepareContext(nonDynamicRun, 'guest'); const nonDynamicVisual = run('graph.js', ['upsert-visual', '--scan-dir', nonDynamicRun, '--context', 'guest', '--root', 'true', '--observation-id', nonDynamicObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; check(Object.keys(readJson(path.join(nonDynamicRun, 'contexts', 'guest', 'graph.json')).visualStates.find(item => item.id === nonDynamicVisual).fingerprint).sort(), ['ability', 'app', 'layoutHash', 'schemaVersion', 'screenshotSha256', 'semantic', 'stableIds', 'stableRoles', 'stableTexts']); const nonDynamicRoot = run('graph.js', ['upsert-reachable', '--scan-dir', nonDynamicRun, '--context', 'guest', '--root', 'true', '--visual-state-id', nonDynamicVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id; fs.writeFileSync(stateFile, 'animated-1'); fs.writeFileSync(restartModeFile, 'preserve'); const nonDynamicFrontier = run('frontier.js', ['add', '--scan-dir', nonDynamicRun, '--context', 'guest', '--from-reachable-state-id', nonDynamicRoot, '--candidate-group-key', 'home/nondynamic-equivalence', '--candidate', JSON.stringify({ type: 'tap', target: '无效区域', fallbackBounds: [400, 0, 500, 100] })]).json.item; const nonDynamicClaim = run('frontier.js', ['claim', '--scan-dir', nonDynamicRun, '--context', 'guest']).json.item; const nonDynamicPrepared = run('execute-frontier.js', ['prepare', '--scan-dir', nonDynamicRun, '--context', 'guest', '--frontier-id', nonDynamicFrontier.id, '--claim-token', nonDynamicClaim.claimToken]).json; let nonDynamicAttempt = nonDynamicPrepared.attempt; check(nonDynamicAttempt.status, 'READY_FOR_ACTION'); check(nonDynamicPrepared.reviewRequest, undefined); check(nonDynamicAttempt.restoreResults[0].equivalenceReviews.length, 0); fs.rmSync(nonDynamicRun, { recursive: true, force: true }); fs.writeFileSync(restartModeFile, '');
  fs.writeFileSync(stateFile, 'animated-1'); fs.writeFileSync(restartModeFile, 'preserve'); const sourceMatchRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-source-match', '--device', 'fake-device', '--context', 'guest']).json.scanDir; const sourceMatchObs = prepareContext(sourceMatchRun, 'guest'); const sourceMatchVisual = run('graph.js', ['upsert-visual', '--scan-dir', sourceMatchRun, '--context', 'guest', '--root', 'true', '--observation-id', sourceMatchObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; const sourceMatchRoot = run('graph.js', ['upsert-reachable', '--scan-dir', sourceMatchRun, '--context', 'guest', '--root', 'true', '--visual-state-id', sourceMatchVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id; const sourceMatchMetrics = readJson(path.join(sourceMatchRun, 'contexts', 'guest', 'metrics.json')); commitEvent(sourceMatchRun, 'faultInjectionCursorUnknown', { contextId: 'guest' }, [{ path: 'contexts/guest/live-cursor.json', op: 'REPLACE', value: { schemaVersion: 1, contextId: 'guest', reachableStateId: null, observationId: null, status: 'UNKNOWN', equivalence: null, epoch: 99, mutationSeq: sourceMatchMetrics.deviceMutationSeq, establishedBy: null, lastValidatedAt: null, updatedAt: new Date().toISOString(), invalidatedReason: 'TEST_CURSOR_UNKNOWN' } }]); const sourceMatchFrontier = run('frontier.js', ['add', '--scan-dir', sourceMatchRun, '--context', 'guest', '--from-reachable-state-id', sourceMatchRoot, '--candidate-group-key', 'home/source-match', '--candidate', JSON.stringify({ type: 'tap', target: '首页', fallbackBounds: [0, 0, 100, 50] })]).json.item; const sourceMatchClaim = run('frontier.js', ['claim', '--scan-dir', sourceMatchRun, '--context', 'guest']).json.item; check(sourceMatchClaim.navigationPlan.mode, 'COLD_REPLAY'); const sourceMatchRestarts = Number(fs.readFileSync(restartCountFile, 'utf8')); const sourceMatched = run('execute-frontier.js', ['prepare', '--scan-dir', sourceMatchRun, '--context', 'guest', '--frontier-id', sourceMatchFrontier.id, '--claim-token', sourceMatchClaim.claimToken]).json; check(sourceMatched.attempt.sourceAcquisitionMode, 'SOURCE_MATCH'); check(['EXACT', 'SOURCE_CONFIRMED'].includes(sourceMatched.attempt.sourceVerification), true); check(Number(fs.readFileSync(restartCountFile, 'utf8')), sourceMatchRestarts); check(readJson(path.join(sourceMatchRun, 'contexts', 'guest', 'metrics.json')).sourceMatchNavigations, 1); fs.rmSync(sourceMatchRun, { recursive: true, force: true }); fs.writeFileSync(restartModeFile, '');
  fs.writeFileSync(stateFile, 'home'); fs.writeFileSync(restartModeFile, ''); const adaptiveRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-adaptive-cursor', '--device', 'fake-device', '--context', 'guest']).json.scanDir; const adaptiveObs = prepareContext(adaptiveRun, 'guest'); const adaptiveVisual = run('graph.js', ['upsert-visual', '--scan-dir', adaptiveRun, '--context', 'guest', '--root', 'true', '--observation-id', adaptiveObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; const adaptiveRoot = run('graph.js', ['upsert-reachable', '--scan-dir', adaptiveRun, '--context', 'guest', '--root', 'true', '--visual-state-id', adaptiveVisual, '--arrival-signature', '{}', '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  for (const group of ['noop-a', 'noop-b']) run('frontier.js', ['add', '--scan-dir', adaptiveRun, '--context', 'guest', '--from-reachable-state-id', adaptiveRoot, '--candidate-group-key', group, '--candidate', JSON.stringify({ type: 'tap', target: group, fallbackBounds: [400, 0, 500, 100] })]); const adaptiveRestarts = Number(fs.readFileSync(restartCountFile, 'utf8'));
  for (let index = 0; index < 2; index += 1) { const claim = run('frontier.js', ['claim', '--scan-dir', adaptiveRun, '--context', 'guest']).json.item; let current = run('execute-frontier.js', ['prepare', '--scan-dir', adaptiveRun, '--context', 'guest', '--frontier-id', claim.id, '--claim-token', claim.claimToken]).json.attempt; check(current.sourceAcquisitionMode, 'LIVE_CURSOR'); current = run('execute-frontier.js', ['act', '--scan-dir', adaptiveRun, '--context', 'guest', '--attempt-id', current.attemptId]).json.attempt; run('execute-frontier.js', ['review-outcome', '--scan-dir', adaptiveRun, '--context', 'guest', '--attempt-id', current.attemptId, '--observation-id', current.reviewObservationId, '--disposition', 'NO_STATE_CHANGE']); }
  check(Number(fs.readFileSync(restartCountFile, 'utf8')), adaptiveRestarts); const adaptiveMetrics = JSON.parse(fs.readFileSync(path.join(adaptiveRun, 'contexts', 'guest', 'metrics.json'), 'utf8')); check(adaptiveMetrics.cursorReuseHits, 2); check(adaptiveMetrics.coldStarts, 1); check(run('finalize-scan.js', ['--scan-dir', adaptiveRun, '--status', 'COMPLETED']).json.scan.status, 'COMPLETED'); fs.rmSync(adaptiveRun, { recursive: true, force: true });
  fs.writeFileSync(stateFile, 'home'); const extensionRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-extension-path', '--device', 'fake-device', '--context', 'guest', '--navigation-policy', 'always-replay', '--app-version', '1.0', '--build-version', '10']).json.scanDir; const extensionRootObs = prepareContext(extensionRun, 'guest'); const extensionRootVisual = run('graph.js', ['upsert-visual', '--scan-dir', extensionRun, '--context', 'guest', '--root', 'true', '--observation-id', extensionRootObs, '--logical-screen-key', 'home', '--name', '首页']).json.visualState.id; const extensionRootState = run('graph.js', ['upsert-reachable', '--scan-dir', extensionRun, '--context', 'guest', '--root', 'true', '--visual-state-id', extensionRootVisual, '--arrival-signature', JSON.stringify({ backBehaviorKey: 'root-exit' }), '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  const extensionFrontier = run('frontier.js', ['add', '--scan-dir', extensionRun, '--context', 'guest', '--from-reachable-state-id', extensionRootState, '--candidate-group-key', 'home/extension-modal', '--candidate', JSON.stringify({ type: 'tap', target: '扩展弹窗', fallbackBounds: [100, 0, 200, 100] })]).json.item; const extensionClaim = run('frontier.js', ['claim', '--scan-dir', extensionRun, '--context', 'guest']).json.item; let extensionAttempt = run('execute-frontier.js', ['prepare', '--scan-dir', extensionRun, '--context', 'guest', '--frontier-id', extensionFrontier.id, '--claim-token', extensionClaim.claimToken]).json.attempt; extensionAttempt = run('execute-frontier.js', ['act', '--scan-dir', extensionRun, '--context', 'guest', '--attempt-id', extensionAttempt.attemptId]).json.attempt; extensionAttempt = run('execute-frontier.js', ['review-outcome', '--scan-dir', extensionRun, '--context', 'guest', '--attempt-id', extensionAttempt.attemptId, '--observation-id', extensionAttempt.reviewObservationId, '--disposition', 'BUSINESS_MODAL']).json.attempt; run('commit-attempt.js', ['--scan-dir', extensionRun, '--attempt-id', extensionAttempt.attemptId, '--logical-screen-key', 'profile-filter', '--name', '筛选条件']); for (const verification of run('verify-path.js', ['list', '--scan-dir', extensionRun, '--context', 'guest']).json.items.filter(item => item.status === 'PENDING')) run('verify-path.js', ['run', '--scan-dir', extensionRun, '--context', 'guest', '--verification-id', verification.verificationId]); run('finalize-scan.js', ['--scan-dir', extensionRun, '--status', 'COMPLETED']); run('register-run.js', ['--scan-dir', extensionRun]);
  const unrelatedRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-unrelated-partial', '--device', 'fake-device', '--contexts', 'guest', '--app-version', '1.0', '--build-version', '10']).json.scanDir; prepareContext(unrelatedRun, 'guest'); run('finalize-scan.js', ['--scan-dir', unrelatedRun, '--status', 'PARTIAL']); run('register-run.js', ['--scan-dir', unrelatedRun]);
  const dashboardFixtureGraphFile = path.join(root, 'maps', 'guest', 'graph.json'); const dashboardFixtureGraph = readJson(dashboardFixtureGraphFile); const dashboardFixtureEdge = dashboardFixtureGraph.edges.find(edge => edge.intent?.target === '我的'); dashboardFixtureEdge.replayability = 'UNSTABLE'; dashboardFixtureEdge.locatorQuality = 'UNRESOLVED'; dashboardFixtureEdge.verification = { ...(dashboardFixtureEdge.verification || {}), replayStatus: 'COLD_REPLAY_VERIFIED' }; fs.writeFileSync(dashboardFixtureGraphFile, `${JSON.stringify(dashboardFixtureGraph, null, 2)}\n`);
  check(run('context.js', ['manual-transition', '--scan-dir', scanDir, '--context', 'guest'], true).status !== 0, true);
  const timeline = fs.readFileSync(path.join(scanDir, 'timeline.jsonl'), 'utf8').trim().split('\n').map(JSON.parse); check(new Set(timeline.map(x => x.eventId)).size, timeline.length);
  const rebuilt = run('rebuild-run.js', ['--scan-dir', scanDir, '--output-dir', path.join(temp, 'rebuilt')]).json; check(rebuilt.ok, true);
  check(run('rebuild-run-index.js', ['--app-map-root', root]).json.indexed, 3);
  const rebuiltIndex = JSON.parse(fs.readFileSync(path.join(root, 'run-index.json'), 'utf8')); check(rebuiltIndex.appKey, 'com-example-demo-test'); const snapshot = run('build-snapshot.js', ['--app-map-root', root]).json; check(snapshot.manifest.status, 'PARTIAL'); check(snapshot.manifest.mapRevisionId, null); check(snapshot.manifest.aggregationPolicy, 'CANONICAL_MAP_ONLY'); check(snapshot.manifest.mapRevisionIds.length, 1); check(snapshot.manifest.sourcePlans.guest.includes('scan-unrelated-partial'), true); check(fs.existsSync(path.join(root, 'snapshots', 'current.json')), true); check(fs.existsSync(path.join(snapshot.snapshotDir, 'manifest.json')), true);
  const snapshotMap = JSON.parse(fs.readFileSync(path.join(snapshot.snapshotDir, 'map.json'), 'utf8')); const snapshotGraph = snapshotMap.contexts.guest; check(snapshotGraph.logicalScreens.some(x => x.id === 'profile'), true); check(snapshotGraph.logicalScreens.find(x => x.id === 'profile').name, '我的'); check(snapshotGraph.reachableStates.some(x => x.id === 'profile-ui-002@guest#002'), true); check(snapshotGraph.reachableStates.filter(x => x.arrivalSignature.expectedBackReachableStateId).every(x => snapshotGraph.reachableStates.some(state => state.id === x.arrivalSignature.expectedBackReachableStateId)), true); const latestPathEdge = snapshotGraph.edges.find(edge => edge.intent?.target === '我的'); check(latestPathEdge.evidence.sourceRunId, 'scan-exploration'); check(latestPathEdge.provenance.some(item => item.runId === 'scan-exploration'), true); check(snapshotGraph.edges.some(edge => edge.intent?.target === '扩展弹窗' && edge.evidence.sourceRunId === 'scan-extension-path'), true); check(snapshotGraph.edges.some(edge => edge.intent?.target === '筛选'), true);
  const dashboard = run('build-dashboard.js', ['--app-map-root', root]).json; check(fs.existsSync(dashboard.dashboardPath), true); const dashboardHtml = fs.readFileSync(dashboard.dashboardPath, 'utf8'); check(dashboardHtml.includes('__SMAP_DASHBOARD_DATA__'), false); check(dashboardHtml.includes(snapshot.manifest.generationId), true);
  const embedded = dashboardHtml.match(/<script id="dashboard-data" type="application\/json">([\s\S]*?)<\/script>/); check(Boolean(embedded), true); const dashboardData = JSON.parse(embedded[1]); check(dashboardData.locale, 'zh-CN'); check(dashboardData.meta.environmentLabel, '测试环境'); check(dashboardData.meta.platformLabel, '鸿蒙'); check(dashboardData.meta.generationLabel.startsWith('地图版本 '), true); check(dashboardData.meta.generationLabel.includes('snapshot-'), false); check(dashboardData.meta.snapshotStatusLabel, '部分可用'); check(dashboardData.overview.edges, snapshotGraph.edges.length); check(dashboardData.contexts[0].logicalGraph.nodes.some(x => x.kind === 'modal' && x.kindLabel === '业务弹窗'), true); check(dashboardData.contexts[0].reachableGraph.edges.some(x => x.evidence.before?.screenshotUrl.startsWith('../runs/')), true); check(dashboardData.contexts[0].reachableGraph.edges.some(x => x.replayabilityLabel === '稳定'), true); check(dashboardData.contexts[0].reachableGraph.edges.some(x => x.label.startsWith('点击')), true); const dashboardFixtureEdgeView = dashboardData.contexts[0].reachableGraph.edges.find(x => x.label === '点击 · 我的'); check(dashboardFixtureEdgeView.replayStatus, 'COLD_REPLAY_VERIFIED'); check(dashboardFixtureEdgeView.replayability, 'UNSTABLE'); check(dashboardFixtureEdgeView.locatorQuality, 'UNRESOLVED'); check(dashboardFixtureEdgeView.lineStyle, 'verified');
  const firstDashboardSha = sha(dashboard.dashboardPath); run('build-dashboard.js', ['--app-map-root', root]); check(sha(dashboard.dashboardPath), firstDashboardSha);
  const pointerFile = path.join(root, 'snapshots', 'current.json'); const validPointer = JSON.parse(fs.readFileSync(pointerFile, 'utf8')); fs.writeFileSync(pointerFile, `${JSON.stringify({ ...validPointer, manifestSha256: 'sha256:corrupted' }, null, 2)}\n`); check(run('build-dashboard.js', ['--app-map-root', root], true).status !== 0, true); check(sha(dashboard.dashboardPath), firstDashboardSha); fs.writeFileSync(pointerFile, `${JSON.stringify(validPointer, null, 2)}\n`);
  const canonicalGuestGraphBeforeEdit = readJson(path.join(root, 'maps', 'guest', 'graph.json')); const canonicalRootState = canonicalGuestGraphBeforeEdit.reachableStates.find(state => Number(state.depth?.pathDepth || 0) === 0); check(run('map-edit.js', ['preview-delete', '--app-map-root', root, '--context', 'guest', '--reachable-state-id', canonicalRootState.id], true).stderr.includes('MAP_EDIT_ROOT_DELETE_REQUIRES_RESET'), true);
  const extensionEdgeBeforeDelete = canonicalGuestGraphBeforeEdit.edges.find(edge => edge.intent?.target === '扩展弹窗'); check(Boolean(extensionEdgeBeforeDelete), true); const canonicalFrontierFile = path.join(root, 'maps', 'guest', 'frontier.json'); const canonicalFrontierBeforeEdit = readJson(canonicalFrontierFile); canonicalFrontierBeforeEdit.items.push({ id: 'frontier-orphan-extension', contextId: 'guest', fromReachableStateId: extensionEdgeBeforeDelete.fromReachableStateId, candidateGroupKey: 'orphan/extension-modal', candidate: extensionEdgeBeforeDelete.intent, priority: {}, status: 'EXPLORED', attempts: 0, createdAt: new Date().toISOString(), reasonCode: null }); fs.writeFileSync(canonicalFrontierFile, `${JSON.stringify(canonicalFrontierBeforeEdit, null, 2)}\n`); const editPreview = run('map-edit.js', ['preview-delete', '--app-map-root', root, '--context', 'guest', '--edge-id', extensionEdgeBeforeDelete.id, '--reason', 'self-test delete extension edge']).json; check(editPreview.summary.counts.edges >= 1, true); check(editPreview.edit.impact.frontierIds.includes('frontier-orphan-extension'), true); check(run('map-edit.js', ['apply-delete', '--app-map-root', root, '--edit-id', editPreview.edit.editId, '--confirm-hash', 'sha256:bad'], true).stderr.includes('MAP_EDIT_CONFIRM_HASH_MISMATCH'), true); const appliedEdit = run('map-edit.js', ['apply-delete', '--app-map-root', root, '--edit-id', editPreview.edit.editId, '--confirm-hash', editPreview.edit.confirmHash]).json; check(appliedEdit.ok, true); check(appliedEdit.previousMapRevisionId, editPreview.edit.beforeMapRevisionId); check(readJson(canonicalFrontierFile).items.some(item => item.id === 'frontier-orphan-extension'), false); const canonicalGraphAfterEdit = readJson(path.join(root, 'maps', 'guest', 'graph.json')); const canonicalMetaAfterEdit = readJson(path.join(root, 'maps', 'guest', 'meta.json')); check(canonicalMetaAfterEdit.candidateCoverage.states.length, canonicalGraphAfterEdit.reachableStates.length); check(canonicalMetaAfterEdit.candidateCoverage.backfillRequiredStateIds.every(id => canonicalGraphAfterEdit.reachableStates.some(state => state.id === id)), true);
  const editedSnapshot = run('build-snapshot.js', ['--app-map-root', root]).json; const editedMap = readJson(path.join(editedSnapshot.snapshotDir, 'map.json')); check(editedMap.contexts.guest.edges.some(edge => edge.intent?.target === '扩展弹窗'), false); const postEditRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-after-map-edit', '--device', 'fake-device', '--context', 'guest']).json.scanDir; check(readJson(path.join(postEditRun, 'contexts', 'guest', 'graph.json')).edges.some(edge => edge.intent?.target === '扩展弹窗'), false); fs.rmSync(postEditRun, { recursive: true, force: true });
  check(run('graph.js', ['record-edge', '--scan-dir', scanDir, '--context', 'guest'], true).status !== 0, true);

  fs.writeFileSync(stateFile, 'home'); const freshRoot = path.join(temp, 'fresh-empty-app-map'); run('init-app-root.js', ['--app-map-root', freshRoot, '--bundle-name', 'com.example.demo', '--entry-ability', 'EntryAbility', '--environment', 'test']); const empty = run('init-scan.js', ['--app-map-root', freshRoot, '--scan-id', 'scan-empty', '--device', 'fake-device', '--contexts', 'guest']).json.scanDir; prepareContext(empty, 'guest'); check(run('finalize-scan.js', ['--scan-dir', empty, '--status', 'COMPLETED'], true).status !== 0, true); const resetPreview = run('map-edit.js', ['preview-reset-context', '--app-map-root', freshRoot, '--context', 'guest']).json; check(run('map-edit.js', ['apply-delete', '--app-map-root', freshRoot, '--edit-id', resetPreview.edit.editId, '--confirm-hash', resetPreview.edit.confirmHash]).json.ok, true);

  fs.writeFileSync(stateFile, 'goal'); const goalRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-goal', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed', '--app-version', '1.0', '--build-version', '10']).json.scanDir;
  const targetPng = path.join(temp, 'target.png'); fs.writeFileSync(targetPng, Buffer.from([137,80,78,71,13,10,26,10])); const goalPreview = run('preview-plan.js', ['--app-map-root', root, '--scan-id', 'scan-goal-preview-confirmed', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed', '--description', '进入账号与安全页面', '--screenshot', targetPng, '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全', '修改密码'] })]).json; check(goalPreview.plan.goal.requiredTexts.length, 2); check(fs.existsSync(path.join(root, 'runs', 'scan-goal-preview-confirmed')), false); const confirmedGoal = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-goal-preview-confirmed', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed', '--description', '进入账号与安全页面', '--screenshot', targetPng, '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全', '修改密码'] }), '--confirmed-plan-hash', goalPreview.planHash]).json; check(confirmedGoal.scan.status, 'PLAN_CONFIRMED'); check(JSON.parse(fs.readFileSync(path.join(confirmedGoal.scanDir, 'goal', 'goal.json'), 'utf8')).goalSpecHash, goalPreview.plan.goal.goalSpecHash); check(JSON.parse(fs.readFileSync(path.join(confirmedGoal.scanDir, 'plan.json'), 'utf8')).planHash, goalPreview.planHash); const invalidGoalRun = run('init-scan.js', ['--app-map-root', root, '--scan-id', 'scan-invalid-goal', '--device', 'fake-device', '--contexts', 'authenticated', '--scan-mode', 'goal-directed']).json.scanDir; const invalidGoal = run('parse-goal.js', ['--scan-dir', invalidGoalRun, '--description', '非法路径预算', '--screenshot', targetPng, '--context', 'authenticated', '--max-verified-paths', '1.5', '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全'] })], true); check(invalidGoal.status !== 0 && invalidGoal.stderr.includes('GOAL_POLICY_INVALID'), true); const goal = run('parse-goal.js', ['--scan-dir', goalRun, '--description', '进入账号与安全页面', '--screenshot', targetPng, '--context', 'authenticated', '--success-criteria', JSON.stringify({ requiredTexts: ['账号与安全', '修改密码'] })]).json.goal;
  const goalObs = prepareContext(goalRun, 'authenticated'); const goalVisual = run('graph.js', ['upsert-visual', '--scan-dir', goalRun, '--context', 'authenticated', '--root', 'true', '--observation-id', goalObs, '--logical-screen-key', 'account-security', '--name', '账号与安全']).json.visualState.id;
  const goalState = run('graph.js', ['upsert-reachable', '--scan-dir', goalRun, '--context', 'authenticated', '--root', 'true', '--visual-state-id', goalVisual, '--arrival-signature', '{}', '--depth', JSON.stringify({ pathDepth: 0, routeDepth: 0, modalDepth: 0 })]).json.reachableState.id;
  const assessment = JSON.stringify({ status: 'STRONG', referenceSha256: goal.referenceScreenshotSha256, observedSha256: sha(path.join(goalRun, 'evidence', 'observations', goalObs, 'screenshot.png')), rationale: 'visual match' });
  const evaluated = run('evaluate-goal.js', ['evaluate', '--scan-dir', goalRun, '--observation-id', goalObs, '--reachable-state-id', goalState, '--visual-assessment', assessment]).json; check(evaluated.runStatus, 'PAUSED');
  run('evaluate-goal.js', ['decide', '--scan-dir', goalRun, '--decision-id', evaluated.decision.decisionId, '--human-decision', 'CONFIRMED_TARGET']);
  const pending = run('verify-goal-path.js', ['prepare', '--scan-dir', goalRun, '--decision-id', evaluated.decision.decisionId]).json.pending; check(pending.status, 'AWAITING_VISUAL_ASSESSMENT');
  const replayAssessment = JSON.stringify({ status: 'STRONG', referenceSha256: goal.referenceScreenshotSha256, observedSha256: sha(path.join(goalRun, 'evidence', 'observations', pending.replayObservationId, 'screenshot.png')), rationale: 'replay visual match' });
  const verified = run('verify-goal-path.js', ['confirm', '--scan-dir', goalRun, '--visual-assessment', replayAssessment]).json; check(verified.goalResult.status, 'FOUND_VERIFIED');
  run('finalize-scan.js', ['--scan-dir', goalRun, '--status', 'COMPLETED']); check(fs.existsSync(path.join(goalRun, 'goal', 'verified-paths.json')), true);
  const legacyGraph = { ...snapshotGraph, schemaVersion: 1, edges: snapshotGraph.edges.map((edge, index) => index === 0 ? { ...edge, action: { type: 'wait', durationMs: 500 } } : edge) };
  let dashboardRejectedLegacy = false; try { assertConsumableGraph(legacyGraph, fail); } catch (error) { dashboardRejectedLegacy = error.code === 'CONSUMER_GRAPH_INVALID'; } check(dashboardRejectedLegacy, true);
  const canonicalLegacyGraphFile = path.join(root, 'maps', 'guest', 'graph.json'); const canonicalLegacyGraph = JSON.parse(fs.readFileSync(canonicalLegacyGraphFile, 'utf8')); canonicalLegacyGraph.schemaVersion = 1; fs.writeFileSync(canonicalLegacyGraphFile, `${JSON.stringify(canonicalLegacyGraph, null, 2)}\n`);
  check(run('build-snapshot.js', ['--app-map-root', root], true).stderr.includes('GRAPH_SCHEMA_UNSUPPORTED'), true);
  console.log(JSON.stringify({ schemaVersion: 1, ok: true, scope: 'full', tests, durationMs: Date.now() - suiteStartedMs, tempRoot: temp }, null, 2));
} finally { if (!process.env.SMAP_KEEP_SELF_TEST) fs.rmSync(temp, { recursive: true, force: true }); }
